### ISSUE TITLE
Workshop 2: Creating Organisations, Projects and Roles

### ISSUE THREAD

**Issue by luisklefsjo** [yldio/joyent-portal#10]
Creating Organisations, Projects and Roles, 
https://docs.google.com/a/make-us-proud.com/document/d/10DzNJC_ja2iBfAN-NfsWI6uGRCFXv9dt3CRoN84qwCA/edit?usp=sharing

**Comment by ajones5876** [comment]
Documented here: https://github.com/yldio/joyent-portal/issues/204 & here: https://github.com/yldio/joyent-portal/issues/216
