### ISSUE TITLE
Clean form after submit

### ISSUE THREAD

**Issue by SaraVieira** [yldio/joyent-portal#1002]
## I'm submitting a...

  - [x] bug report
  - [ ] feature request
  - [ ] design request

## What is the current behavior?
When you create an instance and then go back to the form some of the values are still there

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

Create an instance through the form and then go back to the form

**Comment by ramitos** [comment]
fixed in https://github.com/yldio/joyent-portal/commit/67f36a464be6bc3f084742ad5a6c6392157fbfbc
