### ISSUE TITLE
Create instance, firewall rules: UI improvements

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#1012]
UI:
- [x] Improve padding and margins in table
- [x] Add copy saying that this is not all the firewall rules that could be applied
- [x] Implement empty state (when there are no rules to display). This should be the same as the empty state for packages: https://www.figma.com/file/Mm72VDV9dljgjci40oQAOzKj/CI%3A-Package-Table?node-id=368%3A977

Design: https://www.figma.com/file/b9cR6I1rTObxVQssDPlIjr7n/CI%3A-Firewall

**Comment by AlexJupiter** [comment]
@ramitos what are the ways that a firewall rule could be defined that we aren’t considering at the moment? IP, network and what else?

The reason I am asking is that the copy is going to be along the lines of:

"Other firewall rules may apply as defined by IP, networks........ as well. Please see firewall rule list for more details.

**Comment by ramitos** [comment]
https://apidocs.joyent.com/cloudapi/#firewall-rule-syntax 

> where target can be one of `wildcard`, `ip`, `subnet`, `tag` or `vm`

**Comment by AlexJupiter** [comment]
Okay, so the improved copy is:

"Other firewall rules may apply as defined by wildcard(s), IP(s), subnet(s), tag(s) or VM(s). Please see firewall rule list for more details."
