### ISSUE TITLE
Create instance, affinity: UI improvements

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#1014]
Functionality:
- [x] Make sure rules reflect descriptions outline in [doc](https://docs.google.com/document/d/1BS5EEEzmkgURSMrJzCnZpSxwW5wNj4b2P6zbmrTIMgQ/edit#)
- [x] Only have ability to implement one affinity rule

UI:
- [ ] Try and see if the dropdown can be width of the selected name
- [x] Selected text should be #494949
- [x] Horizontal line should go past arrow

**Comment by SaraVieira** [comment]
@AlexJupiter Try and see if the dropdown can be width of the selected name : This can only be done through some really hack Javascript :(
Link -> http://www.oodlestechnologies.com/blogs/Auto-resize-select-tag-element-width-according-to-option

**Comment by AlexJupiter** [comment]
@SaraVieira okay, let's not worry about it for now then. It's a nicety and something we can revisit at another time. 

If the other points are done I think you can close this issue.
