### ISSUE TITLE
Toggle animation isn't ok on Safari

### ISSUE THREAD

**Issue by AnthonyMann** [yldio/joyent-portal#1026]
## I'm submitting a...

  - [x] bug report
  - [ ] feature request
  - [ ] design request

## What is the current behavior?
Under Safari (and chrome, but to a lesser extend) the Toggle button animation isn't consistent:

![globby_toggle](https://user-images.githubusercontent.com/271955/34999941-f5cd87c8-fada-11e7-9a5c-ebee98f4ef74.gif)

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
Click on the toggle button in Safari, you can also hold the mouse down to see the button expand in size, inconsistently the expanded size get's 'stuck'

## What is the expected behavior?
The toggle switch should remain a consistent size independently of how long the user holds the mouse down

## What is the motivation / use case for changing the behavior?
It's inconsistent and less aesthetically pleasing.

## If the current behavior is a bug, please provide your browser
Safari Version 11.0.2 (13604.4.7.1.6)

**Comment by SaraVieira** [comment]
This was fixed by https://github.com/yldio/joyent-portal/issues/1005
