### ISSUE TITLE
Package table needs to be designed for mobile

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#1035]
## I'm submitting a...

  - [ ] bug report
  - [ ] feature request
  - [x] design request

## What is the current behavior?
![image](https://user-images.githubusercontent.com/7900773/35092805-6cb96952-fc38-11e7-9fbb-9c1dc44f75b2.png)

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
To reproduce this view package selection on a mobile sized screen.

## What is the expected behavior?
A user should be able to choose a package no-matter what device they are using.

**Comment by hollowtf** [comment]
Figma; https://www.figma.com/file/NSR0rhuWGxH7CPUhDhNY41CK/IM-Package?node-id=18%3A834
