### ISSUE TITLE
Wireframing to do list

### ISSUE THREAD

**Issue by antonasdeduchovas** [yldio/joyent-portal#104]
Here is a list of things that require wireframing. I'd like to get more input on this - can we prioritise these things for January?

**Note:** This includes Casey's comments and feedback as per his email
https://docs.google.com/document/d/1FuSPjrBhI3u5FUMVYIiXRScg4psL4PAgf_WKV5JGR3g/edit?usp=sharing

**Comment by luisklefsjo** [comment]
Here is the document from our internal session of prioritising together:

https://docs.google.com/a/make-us-proud.com/document/d/1RFHoFSfkpKI1TvZokTaebnVKzrk9LPVRNUWib_8eLVc/edit?usp=sharing

**Comment by ajones5876** [comment]
Documented in wiki: https://github.com/yldio/joyent-portal/wiki/15.12.16:-Internal-Catch-Up-(prioritising-what's-next)
