### ISSUE TITLE
Plan Usability test sessions

### ISSUE THREAD

**Issue by hollowtf** [yldio/joyent-portal#1073]
Identify areas we'd like to test.
Write test scripts.

**Comment by AlexJupiter** [comment]
My first pass at this: https://docs.google.com/document/d/1T2JZxIgQRkFtzD4MRYbPEfJE6z_ytQSK-DQwFYgaaRw/edit#

It's still really early stage, however it would be great to have some feedback on some of these ideas. 

I'll organise some workshops next week to discuss in more detail.

**Comment by AlexJupiter** [comment]
@ramitos @SaraVieira it would great to have your thoughts on the task for instance management here: 
https://docs.google.com/document/d/1zSInIxUlGlgBuSz21GQ4foyhxmYjBUzlqUeTU74k6Dk/edit#heading=h.21j5flmem12t

**Comment by AlexJupiter** [comment]
Screening survey: https://docs.google.com/forms/d/1BkGydjiTz36lm_KMI4_W8ZCCbHPby64ijoQ_j_ILHIc/edit

**Comment by AlexJupiter** [comment]
Moved this to review and welcoming feedback in regards to this doc: https://docs.google.com/document/d/1zSInIxUlGlgBuSz21GQ4foyhxmYjBUzlqUeTU74k6Dk/edit?ts=5a7876e4#
