### ISSUE TITLE
Implement the management of User Scripts

### ISSUE THREAD

**Issue by hollowtf** [yldio/joyent-portal#1077]
Read only!!!!!!!

Design first.
Then develop

**Comment by hollowtf** [comment]
Designs can be found here: https://www.figma.com/file/PddIucqLf5jfdw4yL3jxvVQv/IM-User-Scripts?node-id=1%3A355

NB. In Instance Management, user scripts are read only.

**Comment by AlexJupiter** [comment]
@hollowtf is this done now?

**Comment by hollowtf** [comment]
All done, just realised this is just a design ticket, not engineering as well.

Can be closed
