### ISSUE TITLE
Navigation Improvements

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#1085]
Two small navigation improvements.

1.) Change "Services" to "Products & Services"

2.) Add a space after "Data Center:" and "Account:"
![image.png](https://images.zenhubusercontent.com/5888921751aa2c305772cb93/04e4c343-1d77-421f-b2e1-42809ba3e48b)

**Comment by ramitos** [comment]
fixed this in https://github.com/yldio/joyent-portal/commit/c39536677bf60097159a9e14151c37cd1c97e1fe
