### ISSUE TITLE
Instances on a network should be in Roboto Mono

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#1089]
## I'm submitting a...

  - [x] bug report
  - [ ] feature request
  - [ ] design request

## What is the current behavior?
Instances are in Libre Franklin:
![image](https://user-images.githubusercontent.com/7900773/35335420-76e0c3a6-010d-11e8-8576-f25851c74e95.png)

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
View this in any browser.

## What is the expected behavior?
The instance text should be in Roboto Mono, as per these designs: https://www.figma.com/file/ZTMvVu1oeHOVY67gtzAxRdAy/CI-Networks?node-id=174%3A12
![image](https://user-images.githubusercontent.com/7900773/35335469-9c8af702-010d-11e8-9e0f-6f349e8460b6.png)

## What is the motivation / use case for changing the behavior?
The build should reflect the designs.

**Comment by ramitos** [comment]
we need to change the theme to declare the monospace font family name
