### ISSUE TITLE
Workshop 3: User / Organisation / Project structure

### ISSUE THREAD

**Issue by luisklefsjo** [yldio/joyent-portal#11]
User / Organisation / Project structure, 
https://docs.google.com/a/make-us-proud.com/document/d/1XPtlyXaYVBcyT0xWvumFBsItyh7VlvQcwk-vRxLq6ps/edit?usp=sharing

**Comment by ajones5876** [comment]
Documented here: https://github.com/yldio/joyent-portal/issues/214
