### ISSUE TITLE
QA Results 1st Feb

### ISSUE THREAD

**Issue by hollowtf** [yldio/joyent-portal#1136]
**Instance Management**

- [x] Instance title in instance list to be semi-bold, not bold
- [x] Labels should be in semi-bold
- [x] Inputs on Instance home should be monospaced
- [ ] Should be copy-to-clipboard on CNS inputs
- [x] Add CNS button should be active state
- [x] Top margin missing on tags title in IM
- [x] Filter input bar too wide, should be 300px
- [x] Vertical Spacing between metadata cards should be 12px

**Instance Creation**

- [x] Space between numberical value and unit of measurement in Package table
- [x] Sorted values not emboldened in Package table
- [x] Top border missing on top card when selected (Package table)
- [x] Margin between package details and package title (Summary) needs to be 12px not 24 px
- [x] Bottom Margin on ‘0 tags’ should be 24px
- [x] Key:value should be written as key–value
- [x] Bottom margin on ‘Metadata Value’ input is too much
- [x] Arrow on Metadata card scaling incorrectly
- [x] When networks is opened, any default selected networks should sit at the top of the array
- [x] Status indicator in network information not vertically aligned to text
- [x] Summary networks should sit sit by side (horizontal) not on top of each other (vertical)
- [x] ‘Firewall Not Enabled’ should be sentence case
- [x] CNS Toggle spacing incorrect when disabled
- [x] CNS summary should just say ‘CNS enabled’
- [x] Affinity rules, component should have 18px type size and 48px line-height
- [x] Top margin on affinity input too much
- [x] Remove “next” button from Affinity
- [x] Inactive arrow on Metadata cards should have ‘Disabled Grey’

**Comment by SaraVieira** [comment]
Inactive arrow on Metadata cards should have ‘Disabled Grey’ -> Problem with icons don't allow us to do this on demand so it has been removed
