### ISSUE TITLE
Design paginations for tables and card list

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#1139]

**Comment by hollowtf** [comment]
Designs for pagination within tables:
https://www.figma.com/file/Bsbx5f2NJTvJQL5mALlfnmHx/Design-Systems?node-id=1%3A1050

Designs for pagination with card view:
https://www.figma.com/file/EXmVggeE7Y2Wkv6wf8rEJwgq/Manage-Custom-Image?node-id=2%3A226

**Comment by hollowtf** [comment]
@ramitos Thoughts?

**Comment by ramitos** [comment]
@hollowtf 👌🔥
