### ISSUE TITLE
User testing

### ISSUE THREAD

**Issue by luisklefsjo** [yldio/joyent-portal#116]
**User testing documention:**
https://drive.google.com/drive/folders/0B03uff53G5KYUGZWS21yRnFnQ00?usp=sharing

**User feedback goes in this document:**
https://docs.google.com/a/make-us-proud.com/spreadsheets/d/1V_qccL1KIybpbVsU19ZWMCacOAG_qSJQm95YRBhtP1I/edit?usp=sharing

**Comment by ajones5876** [comment]
Documented in Wiki: https://github.com/yldio/joyent-portal/wiki/User-Testing
