### ISSUE TITLE
Workshop and document design principles

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#1160]

**Comment by hollowtf** [comment]
https://www.figma.com/file/Bsbx5f2NJTvJQL5mALlfnmHx/Design-Systems?node-id=3790%3A1484

Up for review. Hapy to hear suggestions for the body copy, titles of the principles, metaphor of illustrations, and style of illustrations.

**Comment by yaili** [comment]
Nice one. Since we're not all in one place anymore, @antonasdeduchovas @luisklefsjo could you give
 feedback too if you want? — Don't know Hana's username…

**Comment by antonasdeduchovas** [comment]
@yaili @hollowtf @AlexJupiter I left some feedback, hope it's helpful

**Comment by AlexJupiter** [comment]
This needs an extra review.

**Comment by ramitos** [comment]
@hollowtf @yaili can we close this?
