### ISSUE TITLE
Design the editing of the instance's name

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#1166]
## I'm submitting a...

  - [ ] bug report
  - [ ] feature request
  - [x] design request

## What is the current behavior?
A user chooses the instance's name when they deploy their instance, however there is no way for the user to change this name in the UI after deployment. 

## What is the expected behavior?
A user should be able to change the instance name, most likely on the instance summary.

**Comment by hollowtf** [comment]
Figma: https://www.figma.com/file/Yjd4rPYd3FOPQFWxbS8qKP9o/IM-Home?node-id=15%3A2

**Comment by AlexJupiter** [comment]
@hollowtf can this be closed now? (I'm personally happy with these designs.)

**Comment by hollowtf** [comment]
👍
