### ISSUE TITLE
Indicate that snapshots are not available for all instance types

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#1167]
## I'm submitting a...

  - [ ] bug report
  - [ ] feature request
  - [x] design request

## What is the current behavior?
At the moment, it appears that snapshots are available no matter the instance type, however this is not always the case.

## What is the expected behavior?
If snapshots are not available for an instance type, this should be communicated to the user before they attempt to create a snapshot for that instance type.

**Comment by hollowtf** [comment]
If snapshot is not possible for an instance, then do not show it in the Instance management tabs
