### ISSUE TITLE
Design the flow for resizing a package for VMs

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#1168]
## I'm submitting a...

  - [ ] bug report
  - [ ] feature request
  - [x] design request

## What is the current behavior?
There is no current behaviour for this.

## What is the expected behavior?
For VMs it is possible to resize the instance (choose a different package) after deployment.

**Comment by hollowtf** [comment]
This has already been designed

Figma: https://www.figma.com/file/NSR0rhuWGxH7CPUhDhNY41CK/IM-Package?node-id=1%3A193
