### ISSUE TITLE
Change "Remove" to "Delete" in the quick action menu

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#1169]
## I'm submitting a...

  - [x] bug report
  - [ ] feature request
  - [ ] design request

## What is the current behavior?
![image.png](https://images.zenhubusercontent.com/5888921751aa2c305772cb93/9a0f1cf2-5e82-40c6-a059-f0a6dcf545cf)

## What is the expected behavior?
The word "Remove" should be changed to "Delete". As per the designs:https://www.figma.com/file/JprXZMsU6Lr4iLAG7c6YfBxc/IM-Instance-List?node-id=1%3A424 (Remove also signifies that the instance still exists, you're just detaching it from the account.)

**Comment by ramitos** [comment]
closed in favor of #1179
