### ISSUE TITLE
Users need a confirmation that they are going to delete an object

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#1180]

**Comment by hollowtf** [comment]
Have designed a lightbox as a double confirmation for Instance list and Instance Summary.

Instance List: https://www.figma.com/file/JprXZMsU6Lr4iLAG7c6YfBxc/IM-Instance-List?node-id=251%3A962

Instance Summary: https://www.figma.com/file/Yjd4rPYd3FOPQFWxbS8qKP9o/IM-Home?node-id=114%3A126
