### ISSUE TITLE
Users unsure on the different types of data on instance summary

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#1182]
Specifically, this relates users not understanding what "CN UUID" means.

**Comment by AlexJupiter** [comment]
If we're closing this, where are we recording that this could be a problem?

**Comment by AlexJupiter** [comment]
@hollowtf ?

**Comment by hollowtf** [comment]
let's remember the users we tested with are not typical triton users. 

I am not confident that one atypical user not understanding what CN UUID is a significant problem for us to tackle.
