### ISSUE TITLE
Users wish to see an improved description of networks 

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#1189]

**Comment by hollowtf** [comment]
Is this a relevant ticket? How are we supposed to act on this considering that its information that's returned from API. I propose closing this

**Comment by AlexJupiter** [comment]
@ramitos @hollowtf agreed, it's not something we can act upon. However, we need to work out the correct process for logging issues like this with Joyent. We can bring this up in our next catch up Joyent Product catchup.
