### ISSUE TITLE
Users overlook CNS - stating that it's optional

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#1192]

**Comment by hollowtf** [comment]
Ability to switch off CNS was removed on the Create Instance flow

Figma: https://www.figma.com/file/ehwgeXWi3hnt4CNQNGKRoDws/CI-CNS?node-id=69%3A2270

**Comment by AlexJupiter** [comment]
Before closing this, do we feel that we don't need to explain our reasoning to Casey? Perhaps put in review?

**Comment by hollowtf** [comment]
I feel that Casey is already on board due to the strong steer he gave regarding CNS being on by default.

Why is it you feel we need Casey's feedback on a small alteration to interaction?
