### ISSUE TITLE
Questions for engineering as a result of usability testing:

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#1201]
- [ ] what is the exact definition of "created" in reference to an instance? Does this change when an instance is reprovisioned?
  - [ ] can you technically add a user script into metadata, and will this user script actually work? (this is without the metadata key, reading "user-script")
  - [ ] related to the above question: we should disable the ability to create a metadata key titled "user-script" right? So the user is clear that the only way to input a user script is in the user script section.
  - [ ] is a snapshot key, a snapshot name?

**Comment by AlexJupiter** [comment]
@ramitos @SaraVieira just a reminder about the above, this will help us with our QA. Thanks.

**Comment by ramitos** [comment]
> what is the exact definition of "created" in reference to an instance? Does this change when an instance is reprovisioned?
Instances can't be reprovisioned. They can only be rebooted, or rolled-back (via snapshots). Created never changes, even when rolled back to a snapshot.
> can you technically add a user script into metadata, and will this user script actually work? (this is without the metadata key, reading "user-script")
yes, you can. However, we will override it with wtv you write in the userscript field.
> elated to the above question: we should disable the ability to create a metadata key titled "user-script" right? So the user is clear that the only way to input a user script is in the user script section.
Maybe. Same applies to CNS in tags.
>  is a snapshot key, a snapshot name?
Yes, but it shows `name` now
