### ISSUE TITLE
QA Notes

### ISSUE THREAD

**Issue by hollowtf** [yldio/joyent-portal#1208]
- [x] On tables, line between table header and table contents is too thick. Should be 1 px
- [x] In instance summary, name of instance is shown as package rather than actual name of instance. 
- [x] Instance Summary, status icon and copy are too close to each other, should be 6px
- [x] 'Snapshot key' label should read 'Snapshot name' instead
- [x] Image selection cards have broken and are too small
- [x] When network cards are selected, they should not change order
- [x] Affinity select components are cutting off text e.g. instance name
- [x] Create Affinity button continues to show even when creating an affinity rule
- [x] Space between Image title and type in summary is too much. Should be 12px, not 24px
- [x] show error on create instance
- [x] package sort cpus
- [x] metadata weird char
- [x] tags without value or name
- [x] metadata without value or name
- [x] confirm dialogs to every destructive mutation
- [x] Image selection icons are not clickable
- [x] On quick action buttons in table, only icon is clickable. Make it so whole button is clickable
- [ ] In tables, only name of instance is clickable, make it so whole row is clickable and links to Instance Summary
- [ ] Please rename IP address 1 and IP address 2 to Public and Private respectively
- [x] Image selection icons have broken and not all are correct colour
- [x] Remove bold titles for Instance name, Instance Type, and Package in the Create instance summary
- [x] Make the chevron clickable on image selection and affinity rules dropdowns

**Comment by AlexJupiter** [comment]
@hollowtf was the CNS management tab fixed when you did the QA? Just checking to make sure we didn't miss it.

**Comment by hollowtf** [comment]
Yeah it was and I could view it in full from Instance management

**Comment by AlexJupiter** [comment]
Cool, and this point "Image selection cards have broken and are too small" relates to the version dropdown being broken right? I think this is the only one that would be great to fix before Casey tests later, do you agree?

**Comment by hollowtf** [comment]
yeah, so the fact that the image cards were cutting off the bottom of the text. I think that, if possible, it should be fixed before Casey see it as it is quite a critical bug

**Comment by ramitos** [comment]
is this from `master` or from `my-joy-alpha` branch?

**Comment by ramitos** [comment]
https://github.com/yldio/joyent-portal/issues/1213

**Comment by ramitos** [comment]
https://github.com/yldio/joyent-portal/issues/1214

**Comment by ramitos** [comment]
https://github.com/yldio/joyent-portal/issues/1215

**Comment by ramitos** [comment]
confirm dialogs to every destructive mutation

**Comment by AlexJupiter** [comment]
Some more points:

**Instance List**
- [ ] Filtering should occur immediately, not after typing six letters
- [ ] If no instances in list, an empty state should be present (exact same as snapshots)
- [ ] If no items in a list, the bulk action select should be disabled 
- [ ] Footer should appear at bottom of the screen (currently it always sits in an overflow of the page)

**Instance Management**
- [ ] CNS & DNS tab title, should be changed to just CNS
- [ ] The cursor should not be disabled when using the firewall rule toggle
