### ISSUE TITLE
Correct components in UI Toolkit

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#1226]
@hollowtf will fill this out.

**Comment by hollowtf** [comment]
https://www.figma.com/file/Bsbx5f2NJTvJQL5mALlfnmHx/Design-Systems

- [ ] H4 is incorrect size (too big)
- [ ] Remove small button for now
- [ ] Quick action button not square (should be 48px by 48px)
- [ ] Remove 'Revered Anchor', not used anywhere
- [ ] Remove in paragraph anchor if possible
- [ ] Interior padding of text input should have 12px between border and text, not 18px
- [ ] Do not show example text when text input is active
- [ ] Align input error style with that of one in Figma
- [ ] Remove input warning and input success components
- [ ] Align select error with Figma
- [ ] Remove select warning and select success
- [ ] Radio button labels should be in Regular, not semi-bold
- [ ] Checkbox labels too small, should be body size
- [ ] Target menu content is centred, should be left aligned
- [ ] Outlines on all tables not showing correctly
- [ ] Align message style (to look like a little pop-out menu)
- [ ] Align section list with new style
- [ ] Either align breadcrumb style, or remove
