### ISSUE TITLE
Correct margins in UI Toolkit and consoles

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#1227]
Components in the UI Toolkit should not have margins. Margins should be placed on the implementation of some components.

**Comment by hollowtf** [comment]
A comprehensive set of rules and conditional logic for spacing need to be designed before we begin tidying up the code.

I will start working on this and will keep Sara in the loop with decision made.

For now let's treat this as a design task only and spin off engineering ticket when completed.

**Comment by ramitos** [comment]
> A comprehensive set of rules and conditional logic for spacing need to be designed before we begin tidying up the code

@hollowtf has this been finished already? if so, please close this issue so that we create another one for implementation

**Comment by hollowtf** [comment]
The rules have been defined, i just need to go through and apply those rules to the static figma screens. I've done the Instance management already and am like half way through Create Instance.
