### ISSUE TITLE
Implement create instance section animations

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#1229]
@hollowtf please paste links here.

**Comment by AlexJupiter** [comment]
@hollowtf could you paste the links for the animations above please. We all know how much @SaraVieira loves going into Google Drive..

**Comment by hollowtf** [comment]
Create instance animation can be found here: https://drive.google.com/a/makeusproud.com/file/d/1x3JsnZ-wwHAycfQj0aV-1yPNdAV__Ff_/view?usp=sharing

**Comment by AlexJupiter** [comment]
The plan is for @SaraVieira to start this on Monday (5th March) and then to continue QAing with Tom around his other commitments.

**Comment by ramitos** [comment]
going to close this since this might not be needed with the future CI design refinements
