### ISSUE TITLE
CLI Instructions on create instance: understand scope of work

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#1233]
After completing this ticket, we should understand what we should be designing and the problems the design should solve.

**Comment by AlexJupiter** [comment]
@misterbisson from the workshop we conducted in London in regards to this ticket, I have a couple of questions to allow us to progress with the design:

1.) This is the job statement I have created to summarise the problem we are trying to solve here “When a customer is creating an instance in the UI, they want to learn how they would complete this action in the terminal, so they can complete this action in their terminal more efficiently (and with more functionality) in the future.” Is this job statement accurate in your opinion?

 2.) My understanding is that you can create an instance via the Triton CLI and also the Terraform CLI. In our workshop we focused on the Terraform CLI. To confirm, these CLI instructions should uniquely be related to Terraform, and not the Triton CLI. Does this mean that the majority of users interact with Triton via Terraform at the moment? And if not, why should we not expose how to use the Triton CLI?

**Comment by misterbisson** [comment]
> Is this job statement accurate in your opinion? 

LGTM

> why should we not expose how to use the Triton CLI?

We definitely want to expose Triton CLI. All I was suggesting about Terraform was that we could expose a block describing the `triton_machine` resource that might be used in Terraform. You can see an example in https://github.com/heyawhite/happy-randomizer-terraform/blob/master/main.tf#L30-L39 .

**Comment by misterbisson** [comment]
@AlexJupiter I would add to the above that we should limit our scope to demonstrating this at the time of instance creation (ignoring general instance management). 

I would prioritize showing the `triton instance creation [...]` line with the arguments for user's selected options.

Secondarily, I would love to include showing the Terraform `triton_machine` resource block to create an instance with the user's selected options.

**Comment by AlexJupiter** [comment]
@misterbisson thanks for the clarification.

I understand now that we should focus both on providing education on the Triton CLI and the Terraform CLI. And that the Triton CLI is a priority?

**Comment by misterbisson** [comment]
Correct: the focus is on both Triton CLI and Terraform _in the context of instance creation_ only.

**Comment by AlexJupiter** [comment]
The conversation in regards to this design will be continued here: https://github.com/yldio/joyent-portal/issues/1234
