### ISSUE TITLE
CLI instructions on create instance: create wireframe

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#1234]
When this ticket is closed, we should have outlined a number of potential solutions to the problem.

**Comment by AlexJupiter** [comment]
**First Wireframes**
[This Figma File](https://www.figma.com/file/GWTYkBRQT9QPQyjEmHd0MnZi/CLI-Instructions) outlines three different solutions.

Each solution is broken down here, however do view the figma file to see more information on each.

1.) Floating CLI Instructions
![image](https://user-images.githubusercontent.com/7900773/36550210-aaa36f9a-17ec-11e8-8c58-df534033f50f.png)
This "Floating Action Menu" (FAB) will be fixed near the top of the user's screen. By default the FAB will be collapsed, however once clicked on by the user, the FAB will expand vertically and horizontally. The user then has the option of toggling between Triton and Terraform CLI instructions.

2.) Section ClI Instructions
![image](https://user-images.githubusercontent.com/7900773/36550448-3fbe663e-17ed-11e8-8efb-809c894d5a0e.png)
Here, there is very similar functionality to the previous idea, however this section is always present at the bottom of create instance. It is a challenge to visually distinguish this from the other sections in create instance: some work could be done here to improve this if we think this idea is worth taking forward.

3.) Bottom CLI Instructions
![image](https://user-images.githubusercontent.com/7900773/36550546-7926321c-17ed-11e8-9c07-e9cc32227249.png)
In a similar form of functionality to the chat menu on Facebook, these menus are by default collapsed, and can be expanded by the user to view the specific CLI instruction. It is proposed that only one menu can be open at once. To add more context to what this menu is meant to achieve for the user the subtitle has been added.

In all designs:
- Learn how to configure the Terraform CLI will link [here](https://docs.joyent.com/public-cloud/api-access/cloudapi).
- Learn how to configure Terraform will link [here](https://www.terraform.io/docs/providers/triton/index.html).

Further revisions _could_ include displaying these CLI instructions somewhere inside instance management. 

Questions:
- Does a customer use the "Terraform CLI" or just "Terraform"?
- Are these "CLI Instructions", "Terminal Commands" or something else?

Feedback welcome!

**Comment by misterbisson** [comment]
I think the questions you're asking about where these go is a very important one, and you're right to be looking for places outside the linear flow of instance creation.

There aren't many examples of how this is implemented elsewhere, but GitHub offers one:

![screen shot 2018-02-22 at 8 46 02 am](https://user-images.githubusercontent.com/1709697/36551685-04aa72da-17ad-11e8-89a9-90c96753541e.png)

Clicking the CLI instructions target expands into this:

![screen shot 2018-02-22 at 8 49 07 am](https://user-images.githubusercontent.com/1709697/36551808-5074e510-17ad-11e8-8b75-9ac275507fd6.png)

The key design feature I'm noticing there is that viewing the CLI instructions is a secondary CTA. It's grouped near the primary CTA, but visually minimized compared to the primary. Given how likely it is for our target audience to have seen those in GitHub, perhaps we can explore that a bit?

I think the language used in the mocks is good. One quibble: it's technically a "Terraform resource definition," not "Terraform CLI" instructions, though simply dropping "CLI" from that label will solve that. And a question: if we the design needs a single heading, as option 1 and 2 above, and maybe the GitHub example do, how do we feel about emphasizing "automation" or "integration" in the label?

**Comment by AlexJupiter** [comment]
Explored two more wireframe options:

[4.) Inspired by GitHub](https://www.figma.com/file/GWTYkBRQT9QPQyjEmHd0MnZi/CLI-Instructions?node-id=7%3A514)
A CTA next to the deploy button, opens the CLI instructions below.
![image](https://user-images.githubusercontent.com/7900773/36678000-8978dad0-1b07-11e8-9535-6de2c3d07d21.png)

[5.) Accordion](https://www.figma.com/file/GWTYkBRQT9QPQyjEmHd0MnZi/CLI-Instructions?node-id=7%3A1204)
Using some existing patterns, the CLI instructions are presented above the deploy button
![image](https://user-images.githubusercontent.com/7900773/36678051-a75f0c36-1b07-11e8-824c-5b7b8b625447.png)

Passing over to @hollowtf now to take ideas 1 and 4 forward.

**Comment by hollowtf** [comment]
We have developed 2 ideas further, the floating components, and the section at the bottom of the Create Instance flow.

The floating component variation can be seen here:
https://www.figma.com/file/GWTYkBRQT9QPQyjEmHd0MnZi/CI-CLI-Instructions?node-id=12%3A1661

and the Section at the bottom of Create Instance flow can be seen here (inspired by Github):
https://www.figma.com/file/GWTYkBRQT9QPQyjEmHd0MnZi/CI-CLI-Instructions?node-id=14%3A1422

Both options will require the same effort to build, so decisions can be made purely from an experience and aesthetic perspective. 

Happy to hear any feedback or opinions people have about these. We are looking to move quickly with this and get it built asap.

**Comment by misterbisson** [comment]
There's something interesting about the floating component, but I have a few questions about it:

1. If the CLI/integration instructions are only valid at the time we're ready to deploy, does it make sense to show it all the time?
1. What's the affordance we're giving the user by making this a floater?

In the mocks for the section at the bottom, I think you're right to show both the `triton` CLI command and the Terraform resource details in a single section.

I wonder if "Deploy with CLI" is the right CTA. Isn't it just "see CLI details" or similar, since the user can't actually deploy by clicking that button? I'm also concerned about making it a button, since this is informational and the user can't execute an action with it.

**Comment by misterbisson** [comment]
There's something interesting about the floating component, but I have a few questions about it:

1. If the CLI/integration instructions are only valid at the time we're ready to deploy, does it make sense to show it all the time?
1. What's the affordance we're giving the user by making this a floater?

In the mocks for the section at the bottom, I think you're right to show both the `triton` CLI command and the Terraform resource details in a single section.

I wonder if "Deploy with CLI" is the right CTA. Isn't it just "see CLI details" or similar, since the user can't actually deploy by clicking that button? I'm also concerned about making it a button, since this is informational and the user can't execute an action with it.

**Comment by misterbisson** [comment]
> What's the affordance we're giving the user by making this a floater?

From the call today Tom explained his interest in allowing the user to see the CLI/integration details and I have to admit an interest in that.

However, I also suspect that making that work while also eliminating confusion or distraction form having the persistent floating element follow the user around the instance creation page will be substantially more effort than the more GitHub-like option.

Let's move forward with the GitHub-like option for now while we continue to ponder ways that reveal how the options selected affect the resulting CLI/API integration bits?
