### ISSUE TITLE
Implement small design improvements

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#1241]
- [ ] Design the implementation of 'Flivver' icon. This should be present for every link that opens up a new tab.
- [ ] On disabled "Deploy" button, the user should understand what they need to do to deploy their instance. This is related to the discussion [here](https://docs.google.com/document/d/18-ViBOmjFoS7RRxi0OJblQxpJzHMi3qAOUd-oQs5gkw/edit#heading=h.y23wanh4wzhg). This could also be related to https://github.com/yldio/joyent-portal/issues/1041, and if so, this can be accomplished at a later date. 
- [ ] Define the copy of all placeholder text
- [ ] Define user script description and link to external documentation

**Questions**
- Users do not notice the bulk actions. It has been highlighted that an micro-animation could solve this, however in the meantime, perhaps we can increase the contrast between the background of the bulk action bar, and the background of the page. @hollowtf what do you think?

**Comment by ramitos** [comment]
> Disparity between colon and dash 
fixed

**Comment by ramitos** [comment]
>  Implement error states

fixed

**Comment by ramitos** [comment]
> Network names need to be consistent across instance creation and management

related #1171

**Comment by yaili** [comment]
Regarding colon/dash, the _word_ "key–value" pair should use a dash; how you _display_ a key–value pair can be with a colon. Not sure how this is fixed, but just to clarify.

**Comment by AlexJupiter** [comment]
I updated this ticket and moving into sprint. @hollowtf I can take these two points:
> Define the copy of all placeholder text
> Define user script description and link to external documentation

**Comment by ramitos** [comment]
This has been discussed in this week workshops. Given that most of these will be addressed in future design refinements I'm going to close this.
