### ISSUE TITLE
Implement error states

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#1244]
See this issue for the error states: https://github.com/yldio/joyent-portal/issues/976

As discussed, the validation should happen on the front end on every key stroke. If there is an error, the submit button should also be disabled.

Design: https://www.figma.com/file/Bsbx5f2NJTvJQL5mALlfnmHx/Design-Systems?node-id=1%3A536

**Comment by SaraVieira** [comment]
- [ ] Snapshots
- [ ] Tags
- [ ] Affinity
- [ ] CNS
- [ ] Instance Name

**Comment by AlexJupiter** [comment]
I believe this needs to design reviewed right? And also did we incorporate Khang's feedback that he put in Slack?

**Comment by AlexJupiter** [comment]
@ramitos I updated https://github.com/yldio/joyent-portal/issues/976. All error states should be accurate now. Some have a conditional error state, depending on whether the error occurs on the first input or not.

- [ ] The Affinity error state is also implemented incorrectly. The line of the input should not move upwards. The error messages should push the below content down.
![image](https://user-images.githubusercontent.com/7900773/36779009-6a4990d6-1c66-11e8-9e37-06674412c773.png)
