### ISSUE TITLE
In instance creation, the SSD label shouldn't misalign the column right alignment

### ISSUE THREAD

**Issue by yaili** [yldio/joyent-portal#1269]
## I'm submitting a...

  - [x] bug report
  - [ ] feature request
  - [ ] design request

## What is the current behavior?

In packages with the SSD label, the GB gets misaligned in the table (a few pixels to the left)

**Comment by ramitos** [comment]
fixed by https://github.com/yldio/joyent-portal/commit/255fd67f4816213cd7d6b9a1d4793e44c4deda17
