### ISSUE TITLE
In instance creation, all $/hr values should have the same number of decimal digits

### ISSUE THREAD

**Issue by yaili** [yldio/joyent-portal#1270]
## I'm submitting a...

  - [x] bug report
  - [ ] feature request
  - [ ] design request

## What is the current behavior?

Some have 2, 3 or 4. Can we standardise this?

**Comment by SaraVieira** [comment]
It has been decided to be 4

**Comment by AlexJupiter** [comment]
@SaraVieira Has this been merged? Can I QA?

**Comment by ramitos** [comment]
same answer as https://github.com/yldio/joyent-portal/issues/1304#issuecomment-377249757
