### ISSUE TITLE
In instance creation, if you don't click "Next" and just click the next heading, no summary is shown

### ISSUE THREAD

**Issue by yaili** [yldio/joyent-portal#1272]
Not sure if this is a bug, or just not considered…

- Go to instance create
- Don't add anything to the name, don't touch anything
- Click "Instance type and image"
- The Instance name section closes without either showing an error, or showing a summary

**Comment by ramitos** [comment]
@yaili this is expected. there is no summary to show because there is nothing to show.

If you write something in the name though, and hit "Instance type and image", you'll see a summary.

Please reopen if you find appropriate ;)
