### ISSUE TITLE
In instance creation, when creating an affinity rule, you can't select the first select option

### ISSUE THREAD

**Issue by yaili** [yldio/joyent-portal#1273]
## I'm submitting a...

  - [x] bug report
  - [ ] feature request
  - [ ] design request

## What is the current behavior?

- Go to create instance
- In Affiinity, try to add a rule
- Select only the first options (should, the same, etc.) - you can't, only if you select another option and then the first option again

## What is the expected behavior?

You can select any option

## If the current behavior is a bug, please provide your browser

Chrome Version 64.0.3282.186 (Official Build) (64-bit)

**Comment by ramitos** [comment]
good catch

**Comment by ramitos** [comment]
@yaili this is expected actually. The default options still miss the instance name, hence the disabled "Save". But if you change something and his "Save", you still get a warning because you're missing the instance name.

https://cldup.com/6KD9qeTTp1.png

**Comment by yaili** [comment]
This is not it. I mean, you can't select the first option. If you open the first select and choose "should", nothing gets selected.

**Comment by ramitos** [comment]
I can't really reproduce, please provide more info 😉

**Comment by yaili** [comment]
Let's see if this works:

https://cl.ly/033H1i310K3j
