### ISSUE TITLE
Create mockup for creating image on instance summary

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#1274]
The build currently looks like this: ![image.png](https://images.zenhubusercontent.com/5888921751aa2c305772cb93/82fe4c8c-7652-4ff5-9f62-c3350064f53e)

We need a better solution.

**Comment by hollowtf** [comment]
Done: https://www.figma.com/file/Yjd4rPYd3FOPQFWxbS8qKP9o/IM-Home?node-id=15%3A2
