### ISSUE TITLE
Fuzzy Search Inputs

### ISSUE THREAD

**Issue by alex-windett** [yldio/joyent-portal#128]
Should be driven by an API endpoint

**Comment by alex-windett** [comment]
https://github.com/jdlehman/react-fuzzy-filter
https://github.com/ritz078/react-fuzzy-search

**Comment by tomgco** [comment]
Ideally, it would be good if the component had an interface to retrieve suggestions from an API endpoint, instead of doing all of the hardwork in the browser.
