### ISSUE TITLE
QA Notes

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#1292]
**High Priority**
Highest priority:
- [x] This error should never have happened. We should triple check that the packages change **correctly** between KVm and infrastructure containers. 
![image.png](https://images.zenhubusercontent.com/5888921751aa2c305772cb93/fa4d85f9-b86c-4763-bea1-65631400c3cb)

- [x] There should be an error state, because the Snapshot name cannot start with a special character (https://joyent-portal.slack.com/archives/C5452V3DX/p1519400098000589) ![image.png](https://images.zenhubusercontent.com/5888921751aa2c305772cb93/a1b2fae8-c3f1-4d9e-8020-83b743ed2bf7)
- [x] Implement error states on tag management
![image.png](https://images.zenhubusercontent.com/5888921751aa2c305772cb93/db6268a5-9765-4e59-a062-bfe4c1284bee)
- [x] Add error states to metadata management
![image.png](https://images.zenhubusercontent.com/5888921751aa2c305772cb93/28619421-63ca-4b3a-8837-5de2b28e6f8e)
- [x] Implement error state for duplicate instance
![image.png](https://images.zenhubusercontent.com/5888921751aa2c305772cb93/5d37f1ad-65ba-4369-ac4e-9c2fe848d82b)
- [x] Implement error states on create instance tags
![image.png](https://images.zenhubusercontent.com/5888921751aa2c305772cb93/2e110b5b-bc1a-4b96-931d-97033068a956)
- [x] Implement error states on create instance metadata
![image.png](https://images.zenhubusercontent.com/5888921751aa2c305772cb93/91101da5-d192-4250-afb8-58cf9526cfd5)
- [x] Implement error states on create instance CNS
![image.png](https://images.zenhubusercontent.com/5888921751aa2c305772cb93/8c60c18e-6a59-42ff-90ec-480de5baf183)
- [x] The input should not cut off the text in Affinity rules
![image.png](https://images.zenhubusercontent.com/5888921751aa2c305772cb93/69d4ddce-c424-4c43-ba2f-ac2ab45729ec)
- [x] Implement error states on Affinity rules 
![image.png](https://images.zenhubusercontent.com/5888921751aa2c305772cb93/a9246921-2062-4789-985b-0d9fc79a3e71)

**Medium Priority**
- [x] Should be service name**s**.
![image.png](https://images.zenhubusercontent.com/5888921751aa2c305772cb93/58ddfc2b-7b2a-411f-a884-9db9b4e8c934)
![image.png](https://images.zenhubusercontent.com/5888921751aa2c305772cb93/0f3d2fed-910e-4445-bb98-e3dbde248825)
- [x] This red error state should not appear (it signifies that the user should carry out an action to resolve it, when they might not want to add a service name anymore)
![image.png](https://images.zenhubusercontent.com/5888921751aa2c305772cb93/ff4bfed0-213e-4bcf-97dd-c9e851732226)
- [x] Remove asterix from this sentence and replace with "Please note:". Then remove asterix in the description (reason being, when the CNS is disabled, the asterix points to nothing)
![image.png](https://images.zenhubusercontent.com/5888921751aa2c305772cb93/59862f74-d734-4613-8484-2a4180fd40ee)
- [x] Name, should not be capitalised, and should also be plural
![image.png](https://images.zenhubusercontent.com/5888921751aa2c305772cb93/116a30da-db0e-4cb0-b1b8-58b5fb827281)

**Low Priority**
- [x] This error message shouldn't appear. The error state for instance names should appear, as well as the empty state.
![image.png](https://images.zenhubusercontent.com/5888921751aa2c305772cb93/22faae1b-aed4-4a01-8469-c6662004fd90)
- [x] Cursor should be pointer when over the name of a package
![image.png](https://images.zenhubusercontent.com/5888921751aa2c305772cb93/5a8d5eb9-67e1-4903-8524-a648623d8f19)

**Questions**
- Are there any character limits on any of the inputs?

**Comment by SaraVieira** [comment]
No, we don't have any  character limit in any I think
