### ISSUE TITLE
create new project

### ISSUE THREAD

**Issue by ramitos** [yldio/joyent-portal#130]
maybe use redux-form

[![](https://cldup.com/ILLXj1byTb.png)](https://app.zeplin.io/project.html#pid=57f679d046c2a775539554a2&sid=5845a1561e5ba4575d8478a3)

[![](https://cldup.com/t_SCuCwQAP.png)](https://app.zeplin.io/project.html#pid=57f679d046c2a775539554a2&sid=5845a15650f4bca82959ac58)

[![](https://cldup.com/hNekFpvgeI.png)](https://app.zeplin.io/project.html#pid=57f679d046c2a775539554a2&sid=5845a1531e5ba4575d84785a)

[![](https://cldup.com/zhQ4yAbR42.png)](https://app.zeplin.io/project.html#pid=57f679d046c2a775539554a2&sid=5845a153b98ca6c863fbd8f2)

[![](https://cldup.com/lIFMIKLXBW.png)](https://app.zeplin.io/project.html#pid=57f679d046c2a775539554a2&sid=5845a15bd138867d6d740a91)

[![](https://cldup.com/GwK-YqpJIp.png)](https://app.zeplin.io/project.html#pid=57f679d046c2a775539554a2&sid=5845a152d138867d6d740a48)

**Comment by tomgco** [comment]
I have used redux form in the past, and wasn't too happy with it. But I am happy for us to look into it.

**Comment by ramitos** [comment]
@tomgco yeah, I never used it :/

Do you have any suggestion?

**Comment by tomgco** [comment]
> @tomgco yeah, I never used it :/
> 
> Do you have any suggestion?

No, but only experience with redux-forms.

**Comment by ramitos** [comment]
updated the issue description with images linked to the zeplin screens

**Comment by ramitos** [comment]
On hold while we finish #139. Current progress can be found @ https://github.com/yldio/joyent-portal/tree/ramos/create-project
