### ISSUE TITLE
"Products & Services" nav label moves up when clicked

### ISSUE THREAD

**Issue by yaili** [yldio/joyent-portal#1304]
## I'm submitting a...

  - [x] bug report
  - [ ] feature request
  - [ ] design request

## What is the current behavior?

When you click Products & Services on the nav, desktop, the text label and icon move up a few pixels

This also happens in "Data Center"

## What is the expected behavior?

I expected this to not move when clicked. It looks like an error.

**Comment by hollowtf** [comment]
Quick question, where did the term 'Products and Services' come from? It's not very consumer friendly language as most people would consider products actual 3D objects. Sounds like this came out of the mind of a Digital product Designer.

Can we scrap it for now and just go with Services until we find something more appropriate?

**Comment by misterbisson** [comment]
> Quick question, where did the term 'Products and Services' come from?

I got feedback from others that "services" was an overloaded term. Some of this was in the context of our CoPilot work, in which "services" had a specific meaning, but the problem will persist with the introduction of TSGs, Triton Service Groups, where services will continue to have a specific meaning that's different from the services in the menu.

**Comment by AlexJupiter** [comment]
@SaraVieira @ramitos is this in the pipeline "In Review" because it needs to be QA'd? If so has this been merged and can I carry out this QA?

**Comment by ramitos** [comment]
With the recent changes, it has become more difficult to setup the project. Working on it
