### ISSUE TITLE
Prioritise feedback from Khang from web console demo

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#1316]
Following on from Tom's notes, I did a prioritisation of this feedback: https://docs.google.com/document/d/1ij0Of0mlQd_hb2RBqx_fRIEscuJ5Y3kPv9jk6smsS-k/edit#

The aim of this was to determine new design tasks in response to this feedback.

Feedback and comments on this prioritisation is welcome.

**Comment by yaili** [comment]
@hollowtf @SaraVieira @ramitos please review

**Comment by AlexJupiter** [comment]
Updated that doc, and also experimented with putting the feedback in the new confidence product: https://confidence.now.sh/project?project=p-SkF_Ep9dz

**Comment by ramitos** [comment]
Just reviewed @yaili

**Comment by yaili** [comment]
@ramitos thank you!
