### ISSUE TITLE
services topology

### ISSUE THREAD

**Issue by ramitos** [yldio/joyent-portal#132]
using @tomgco  graph

[![](https://cldup.com/zsyU5TUFkW.png)](https://app.zeplin.io/project.html#pid=57f679d046c2a775539554a2&sid=5846b5a2be8201f062d19ae1)

[![](https://cldup.com/MD6ki2WMZb.png)](https://app.zeplin.io/project.html#pid=57f679d046c2a775539554a2&sid=5845a17334349c5048bd4a61)

**Comment by tomgco** [comment]
See https://github.com/yldio/joyent-portal/tree/master/spikes/architecture/d3-revamp
![screenshot from 2016-12-06 17-03-28](https://cloud.githubusercontent.com/assets/524382/20936109/4508ebda-bbd9-11e6-9561-baa1f7fcc80c.png)

**Comment by ramitos** [comment]
added screenshots linked to the zeplin screens

**Comment by tomgco** [comment]
Initially work has been done on this and commit in, we have new designs so the component needs to be updated.
