### ISSUE TITLE
Create Instance flow redesign

### ISSUE THREAD

**Issue by hollowtf** [yldio/joyent-portal#1325]
Redesign the CI flow to accommodate user behaviours of freely skipping between sections.
Include mandatory/optional notations.
Add affordance for section headers.

**Comment by hollowtf** [comment]
First pass complete; mainly focussing on the style and affordance.

Thoughts and opinions welcome as always.

Figma: https://www.figma.com/file/UXIV7EG06UDEeP4NFlsy0ohk/CI-Summary?node-id=263%3A743

**Comment by AlexJupiter** [comment]
This is such a **huge** improvement!!! :)

Couple of questions:

1.) Why doesn't the width of the section cards stick to the grid?
![image](https://user-images.githubusercontent.com/7900773/38079224-48a9588a-3336-11e8-8eac-6d8878ca5a16.png)

2.) Why have we added verbs back into the section titles? Like "attach"?

3.) Are we not including "optional" settings to try and encourage the user to discover features? Related to the conversation with Casey whilst he was here?
