### ISSUE TITLE
Reverse position of CNS Service name and add new CNS service name components

### ISSUE THREAD

**Issue by hollowtf** [yldio/joyent-portal#1331]
On CI and IM

**Comment by hollowtf** [comment]
https://www.figma.com/file/ehwgeXWi3hnt4CNQNGKRoDws/CI-CNS?node-id=394%3A2636

**Comment by AlexJupiter** [comment]
Looking good to me! Happy to close this. And I shall add a new ticket in the backlog to implement this design revision.
