### ISSUE TITLE
Portal doesn't load due to incorrect Datacenter name

### ISSUE THREAD

**Issue by Smithx10** [yldio/joyent-portal#1342]
## I'm submitting a...

* [ X] bug report
* [ ] feature request
* [ ] design request

While following the steps in https://github.com/yldio/joyent-portal/blob/master/running.md with an on-prem triton install, I got the following error.  

My cloudapi url is : https://cloudapi.tritonhost.com, and it seems like it may be parsing "cloudapi" from that string and setting it as the datacenter name as well.  

Is there a configuration where I can set these values?

```
Debug: error, /datacenters/cloudapi 
    {"code":"ResourceNotFound","message":"cloudapi is not an available datacenter"}
Debug: handler, error 
    Error: cloudapi is not an available datacenter
    at CloudApi._request (/git/joyent-portal/node_modules/cloudapi-gql/lib/cloudapi.js:120:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
Debug: error, graqhql-error 
    {"errors":[{"message":"cloudapi is not an available datacenter","locations":[{"line":2,"column":3}],"path":["datacenter"]}],"data":{"datacenter":null,"account":{"login":"smith","__typename":"User"}}}
```

**Comment by ramitos** [comment]
@Smithx10 YLD is building this under contract to Joyent and cannot provide support at this time. Can you please direct your question to support@joyent.com or sales@joyent.com?

**Comment by Smithx10** [comment]
Thanks.
