### ISSUE TITLE
Design the Post-action confirmation page

### ISSUE THREAD

**Issue by hollowtf** [yldio/joyent-portal#1349]
Design the page users will see when they have successfully deployed an object. Attempt to white label it so it may be used whenever any type of object is created.

**Comment by hollowtf** [comment]
https://www.figma.com/file/e3QV20jvtBmrOSecMII4GeG4/Template-Post-action

**Comment by AlexJupiter** [comment]
- [ ] As discussed this morning, we need to understand the UX around this, specifically in terms of where this is going to appear in the user journey.

**Comment by misterbisson** [comment]
I had commented in the Figma file with a question about the language. At the time this page is displayed, the deployment or provision or whatever action was requested probably isn't yet actually complete.

**Comment by AlexJupiter** [comment]
I changed the language to "You are attempting to deploy [object]" as an improvement.
