### ISSUE TITLE
What is the user's first experience of the web console going to be?

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#1358]
This is on-boarding, without the signing up. It has been expressed that this is important for private cloud users. The first step of this is the implementation of empty states, which we have already done.

This is expected to be picked up in the beginning of May.

**Comment by AlexJupiter** [comment]
Improved the empty state for instances here: https://www.figma.com/file/JprXZMsU6Lr4iLAG7c6YfBxc/IM-Instance-List?node-id=47%3A222

I then also updated the design system with a template for empty states going forward: https://www.figma.com/file/Bsbx5f2NJTvJQL5mALlfnmHx/Design-Systems?node-id=1320%3A2322

Until the hub page is defined, I think this is all that can be done here for now.

**Comment by AlexJupiter** [comment]
Moving this to review to get opinions on this proposed change in the empty states.

@yaili as per your question on the Figma file, this is what the previous empty state was:
![image](https://user-images.githubusercontent.com/7900773/39004280-436ac246-43fd-11e8-8080-cb37af82e9cb.png)

**Comment by AlexJupiter** [comment]
@yaili this would appear anywhere there is an empty table of objects when the user has the ability to create an object of this type. So for example:
- Instance table
- Service group table
- Instance template table

Due to the nature of how images are represented in a list, the empty state will be slightly different here, and I am proposing an empty state for this [here](https://www.figma.com/file/EXmVggeE7Y2Wkv6wf8rEJwgq/Manage-Custom-Image?node-id=131%3A393).

On a side note, I will be catching up with @antonasdeduchovas, and amongst other things, we will be  discussing the implementation of the Salamander into the empty states.

**Comment by AlexJupiter** [comment]
In relation to the Salamander, the [Design Persona framework](http://aarronwalter.com/design-personas/), as defined by MailChimp, could be a good place to start in terms of thinking about the mascot's implementation.

**Comment by hollowtf** [comment]
We will create further tickets about this when necessary
