### ISSUE TITLE
Design the front page of the console(s)

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#1359]
EC2 has this:
![image.png](https://images.zenhubusercontent.com/5888921751aa2c305772cb93/6ecce5fd-2445-4815-bf46-1b78e38eb5f3)

What is going to be the alternative on Triton?

I'm unsure on the scope of this, however it is potentially tabled to discuss with Casey in the workshop on the 30th April.

**Comment by heyawhite** [comment]
Adding myself to follow this conversation. Also, below is Joyent's current "homepage" after logged in to the portal.

![my.joyent.com portal dashboard, post-login](https://user-images.githubusercontent.com/2766281/38632775-b126ab2e-3d8b-11e8-9069-a49f5a3b5ef5.png)

**Comment by misterbisson** [comment]
@AlexJupiter slight correction: AWS' post-login console front page is this:

![screen shot 2018-04-11 at 10 28 10 am](https://user-images.githubusercontent.com/1709697/38633023-38edefe0-3d73-11e8-975b-ecff300d0962.png)

The URL of that example is https://us-west-2.console.aws.amazon.com/console/home?region=us-west-2

**Comment by AlexJupiter** [comment]
Created this Information Architecture, which illustrates a potential user flow through the product: https://whimsical.co/8hdjuCEPHeUKpZH6fm3mFf

This helps to visualise the context of any front pages/hub pages. After the exercise, I need clarification on whether the hub page should live on the compute level, or above compute and so take in information from Manta and other product.

**Comment by misterbisson** [comment]
> the option of each console having it's own homepage as well

My instinct is to avoid that, but can you say more about what the intent is?

> I initially highlighted the EC2 console homepage

That's the EC2 marketing page and serves a very different purpose from the consoles.

> clarification on whether the hub page should live on the compute level

Let's focus on having a single top-level hub for all services, rather than sub-hubs by category.

**Comment by AlexJupiter** [comment]
> can you say more about what the intent is?
I was initially misled by thinking that the marketing page was the front page of the consoles, so my initial intent was also misplaced. Thank you for the clarification.

> Let's focus on having a single top-level hub for all services, rather than sub-hubs by category.
Okay, and so that would be the equivalent: of https://us-west-2.console.aws.amazon.com/console/home?region=us-west-2. Then, from this page, whenever a user clicks on any of the product and services on offer, they would most likely be taken to a list of objects in a specific console

**Comment by AlexJupiter** [comment]
We conducted some initial research on this topic:
- Here is a [Google Doc](https://docs.google.com/document/d/1KtDQMYJ740CeBcmUJGsLKAyvvtnqzfpujGqhGNM58nk/edit#) illustrating some proposed job statements, as well as some inspiration from other products
- following the above, we conducted a brief sketching workshop in this [inVision product](https://projects.invisionapp.com/freehand/document/T8s2anNlE)

Next steps:
- Understand the technical limitations of this page. What metrics and activities can be brought in?

**Comment by AlexJupiter** [comment]
As discussed in the [19/04/18 weekly catchup](https://docs.google.com/document/d/10oyH_mlFXokKYLF4tdhjJwbGemrjEaHC35JAq1_7JMM/edit) this issue can be picked up again during the London Workshop on 30/04/18.

**Comment by AlexJupiter** [comment]
This [Information Architecture](https://whimsical.co/8hdjuCEPHeUKpZH6fm3mFf) diagram should be useful reference when this issue is picked up.
