### ISSUE TITLE
Copy Update: Package descriptions

### ISSUE THREAD

**Issue by heyawhite** [yldio/joyent-portal#1361]
## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [ ] design request
* [x] copy request

## What is the current copy?

**Package Description**
Copy: A package defines the specs of your instance. On Triton, packages can only increase in size.
Read the docs link: https://docs.joyent.com/public-cloud/instances/packages/sizing

## What is the suggested new copy?

**Package Description**
Copy: Triton packages determine the resources allocated to your instance including RAM, disk space, CPU, IO_PRIORITY, and more. Once set, package size can only increase.
Read the docs link: https://docs.joyent.com/public-cloud/instances/packages

### Logic behind the update

The new text better describes what a package is used for, by specifying what specs a package defines. Additionally, the link goes to the main packages page which has a better overview of what packages are.

## Related documents
_In this section, include any Figma files, PRs, code snippets, or other relevant documents_.

[Figma file](https://www.figma.com/file/Mm72VDV9dljgjci40oQAOzKj/CI%3A-Package-Table?node-id=415%3A549)

**Comment by AlexJupiter** [comment]
@heyawhite what do you think about having a section in this template for links to the Figma file and/or code where possible?

**Comment by heyawhite** [comment]
@AlexJupiter absolutely. I'll update the ticket with that information (where I have it).

**Comment by AlexJupiter** [comment]
I also just created a new Copy tag for this repo so we can easily sort all copy related issues.

**Comment by heyawhite** [comment]
@AlexJupiter heads up, I don't have the power to add labels (or really do anything that's in the sidebar). Not sure if that's intentional or not.
