### ISSUE TITLE
Define the process around correct copywriting

### ISSUE THREAD

**Issue by hollowtf** [yldio/joyent-portal#1371]
How might we catalogue and update all copy in the product and ensure that changes to copy are not lost in a google doc. 
Should be aiming to get as close to 'code as a source of truth' as possible.

**Comment by AlexJupiter** [comment]
@heyawhite has created an issue template that can be used to help this process: https://github.com/yldio/joyent-portal/issues/1361

**Comment by AlexJupiter** [comment]
A proposed solution is here: https://github.com/yldio/joyent-portal/issues/1381
