### ISSUE TITLE
Understand the experience implications of implementing the new navigation

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#1376]
It is understood that the path forward is to implement the [new navigation](https://www.figma.com/file/eJeaYf26mWEWP4hvaLowny0j/Navigation-Prototype?node-id=2%3A381) on the current my.joyent portal: with the new navigation allowing the user to navigate to the new consoles such as VMs and Containers, and Images. 

With the experiences of the old portal being mixed with the experiences of the new consoles; we are trying to understand how this is going to impact the overall user experience of using Triton so we can assess any further work on this topic.

Current questions:
- will the my.joyent sidebar remain?
- should the user be able to switch between old consoles and new consoles?
- the homepage of my.joyent is currently a dashboard, will this also be the case with this new implementation of Triton?

**Comment by misterbisson** [comment]
> will the my.joyent sidebar remain?

Ideally we’d remove it to reduce confusion with dual navigation. 

> should the user be able to switch between old consoles and new consoles?

Yes, for a period of time. 


> the homepage of my.joyent is currently a dashboard, will this also be the case with this new implementation of Triton?

When posed like this, it seems to prioritize the task of building a new landing page/dashboard users would be sent to immediately after login if they haven’t identified a console via directed navigation to it.

**Comment by AlexJupiter** [comment]
Linking this issue with another one currently sitting in the design backlog: https://github.com/yldio/joyent-portal/issues/1359
