### ISSUE TITLE
Copy update: image creation

### ISSUE THREAD

**Issue by heyawhite** [yldio/joyent-portal#1383]
## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [ ] design request
* [x] copy request

## What is the current copy?

Copy: Choose the instance you would like to use as a pattern to build your custom image from. Any future alterations you make to that instance will not affect your existing images. Read the docs

## What is the suggested new copy?

Copy: Choose the instance to use as a template for building a custom image. Any future alterations to the chosen instance will not affect existing images.

### Logic behind the update

This description needs to be improved to communicate what images are used for. I prefer "template" over "pattern." 

## Related documents

_In this section, include any Figma files, PRs, code snippets, or other relevant documents_.

+ [Create Image Figma File](https://www.figma.com/file/0kBPSGHEuKCPwpygrrqnPzaH/Create-Custom-Image?node-id=1%3A105)

**Comment by fabiommmoreira** [comment]
Won't fix: this feature wasn't developed
