### ISSUE TITLE
QA Notes for create instance

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#1387]
**General**
- [x] Fix typo in "Collapse" CTA
- [x] Expand & Collapse should not be red on click, the colour should be #436275
- [x] Remove all verbs from section title. For example, remove "Select", "Add", and "Enable".                   

**Instance type and image**
- [x] Cursor should be pointer when hovering over the version dropdown
- [ ] If no version is selected, then there should be no blue border. So not this: ![image.png](https://images.zenhubusercontent.com/5888921751aa2c305772cb93/2c4b1f7d-5c39-4776-aed9-f0b223e7c5c6)
- [x] The selected tab should also have an underline, like [here](https://www.figma.com/file/UXIV7EG06UDEeP4NFlsy0ohk/CI-Summary?node-id=263%3A1682): ![image.png](https://images.zenhubusercontent.com/5888921751aa2c305772cb93/4b2a4283-6cb2-421a-b84d-b09815713df4)

**Tags**
- [ ] I believe a tag cannot be created with a value. So the create button should not be active like it is below:
![image.png](https://images.zenhubusercontent.com/5888921751aa2c305772cb93/fff79a63-2b1d-45f6-a9cd-8939919dc10b)

**CNS**
- [x] If instance name is defined, then the instance name should appear in the hostnames, and not `inst-name`:
![image.png](https://images.zenhubusercontent.com/5888921751aa2c305772cb93/c95016a4-ad41-4129-ba88-143d8b7e3b50) -- if not possible to do easily, don't fix

**Affinity rules**
- [ ] All dropdowns should have the same spacing between the text, and the chevron -- lower priority
- [ ] Chosen dropdowns should be same colour as text, not greyed out:
![image.png](https://images.zenhubusercontent.com/5888921751aa2c305772cb93/bc88fd83-fc22-4fdc-91f8-355def1b388d)

~~Points for discussion
When a section is collapsed, the top of the browser window should be level with the top of the collapsed section?
Change "Collapse" to "Save and Collapse". This would be the same for the primary CTA for a section. Then upon clicking the CTA the card would just collapse, and not go to the next section (I personally think that automatically heading to the next section is very confusing). 
Should we design a new collapsed state for user scripts?
Is "Firewall not enabled" descriptive enough? Should we highlight how many active firewall rules are applied to the instance as well?
Is "CNS anabled" descriptive enough? Should we highlight how many CNS Service names have been added?
Related to the above two points, firewall rules and CNS are the only two collapsed states with a big green tick. Doesn't this draw unnecessary attention?~~ ![image.png](https://images.zenhubusercontent.com/5888921751aa2c305772cb93/d0934dac-6efd-4bca-9f04-2eaf74a6f7af)

**Comment by yaili** [comment]
We've updated the ticket to only include medium/high priority items.

**Comment by johnytiago** [comment]
@AlexJupiter 
>  Expand & Collapse should not be red on click, the colour should be #436275

Is this color code in the UI toolkit. I can't find it there.

**Comment by AlexJupiter** [comment]
@johnytiago 

- The typo I refer to was due to the spelling of the word "collapse" being incorrect. Perhaps this has been fixed already?
- I don't know if that colour is in the coded UI Toolkit, but it is in [Figma](https://www.figma.com/file/Bsbx5f2NJTvJQL5mALlfnmHx/Design-Systems?node-id=1%3A458):
![image](https://user-images.githubusercontent.com/7900773/39751091-063bed1c-52af-11e8-9f7b-96344e4438ed.png)

**Comment by ramitos** [comment]
- [ ] Margin in sections
- [ ] images button
- [ ] reboot button 
- [ ] optional name (also, it's considering it saved incorrectly)
- [ ] broken images cards
- [ ] edit name should be Save, not Add
- [ ] Snapshots disabled in HVM
- [ ] User scripts editor too big

**Comment by AlexJupiter** [comment]
@johnytiago is this the ticket you're working on at the moment?

**Comment by johnytiago** [comment]
Atm, I'm finishing #1392, then will move onto this one. ;)

**Comment by johnytiago** [comment]
> If no version is selected, then there should be no blue border. So not this: 

This problem has been noted here #1268 before. According to @fabiommmoreira this is the proper browser behaviour, this serves the purpose of allowing for arrow selection. If you still want to remove the outline on the first blur. Let us know.
