### ISSUE TITLE
spike option and select libraries

### ISSUE THREAD

**Issue by ramitos** [yldio/joyent-portal#140]

**Comment by alex-windett** [comment]
Also referenced in #128 and #129

**Comment by alex-windett** [comment]
Narrowed it down to [react-selectize](furqanzafar.github.io/react-selectize/) and [react-select](https://github.com/JedWatson/react-select). There are really brief notes in the readme of each spike, but think we should go with react-select. They are both fairly similar, except react-select has an async option out of the box. 

However, they both require external stylesheets to get a basic layout - obviously we would have to override / alter the original for our needs
