### ISSUE TITLE
Bugs from user-testing

### ISSUE THREAD

**Issue by hollowtf** [yldio/joyent-portal#1416]
- [x] Package table, vCPU is missing
- [x] Package table, Storage Optimised icon is incorrect
- [x] Tags, delete cross still visible and clickable when the Tags card is collapsed. This should not be the case
- [x] User scripts, code block component should only have 5 empty lines when opened
- [x] Firewalls, implement checkboxes in the place of the toggles for "Enable firewalls" and "View inactive rules"
- [x] CNS, remove the browser default disabled cursor when hovering over the CNS urls
- [ ] CNS, 'Network hostnames' not showing despite instance being attached to additional networks
- [x] CNS, CNS Service Name tag should go below the input
- [x] General, 'Read the docs' link collapses the card
- [x] General, On click, anchor state goes grey, consult design systems for correct colours

**Comment by AlexJupiter** [comment]
- [ ] Align all new CNS service names to the left, not like this: 
![image](https://user-images.githubusercontent.com/7900773/40117878-2a8d688c-5910-11e8-9d83-3070d122e102.png)

**Comment by johnytiago** [comment]
That @AlexJupiter is fixed here #1420

**Comment by AlexJupiter** [comment]
@johnytiago alright, thanks, my fault!

**Comment by johnytiago** [comment]
It's not merged yet, so technically is not fixed yet! 😂

**Comment by johnytiago** [comment]
> CNS, 'Network hostnames' not showing despite instance being attached to additional networks

@hollowtf can you help me better understand this bug?

**Comment by hollowtf** [comment]
Other than the the CNS network issue, all other bugs are fixed.

CNS issue will be opened in separate ticket
