### ISSUE TITLE
publish chartjs box and whiskers plugin

### ISSUE THREAD

**Issue by ramitos** [yldio/joyent-portal#142]

**Comment by tomgco** [comment]
Have published the first iteration here: https://www.npmjs.com/package/chartjs-chart-box-plot as `chartjs-chart-box-plot`. The build on circleci is: https://circleci.com/gh/yldio/chartjs-chart-box-plot/tree/master.

As this is now deployed (as a pre-release only), there is a few things that we need to do.

- [ ] Add a readme that makes sense
- [ ] Actually make it work in a component
- [ ] Move code to ES2016 (babel transforms exist already)
