### ISSUE TITLE
Move storybook config to within a component's directory

### ISSUE THREAD

**Issue by tomgco** [yldio/joyent-portal#143]
Currently the storybook config can be found in one massive, monolithic configuration.

Lets use something like: https://github.com/auth0-extensions/auth0-extension-ui/blob/master/.storybook/config.js#L3

To move the story's inline with the actual components.

**Comment by alex-windett** [comment]
https://github.com/yldio/joyent-portal/commit/900268ab27ca0814cf014d3eb1f607e3375ff4f3

A `story.js` should now be placed in component directory
