### ISSUE TITLE
Spacing action items

### ISSUE THREAD

**Issue by ramitos** [yldio/joyent-portal#144]
- [x] implement `unitCalc` that is similar to `remcalc` that calculates rems based on a baseline (where the unit size is a constant)
 - [x] show baseline grid in development (https://github.com/jkeyes/baseline)
 - [x] implement `<h1>`, `<h2>`, `<h3>`, `<h4>`, `<h5>`, `<p>` and `<small>` and use that *everywhere* https://github.com/yldio/joyent-portal/commit/299f7e2282211640c8f63177105889b53d397d01
 - [x] use font from wireframes and fallback
 - [x] go through every padding/margin and make sure it uses baseline units

N.B center is 6 baseline units above geometrical center

**Comment by alex-windett** [comment]
Was thinking the same thing for a `unitCalc` function - but then would setting base font size as 16px and then instead of using our `remCalc` function we can just do `1rem`, `2rem`, `3rem`?

https://css-tricks.com/rems-ems/

**Comment by tomgco** [comment]
> Was thinking the same thing for a unitCalc function - but then would setting base font size as 16px and then instead of using our remCalc function we can just do 1rem, 2rem, 3rem?

I really like the idea of using the rem system for this, makes the code much easier to rationalise from the design, the only issue I see though is seeing if zeplin supports this, otherwise we are converting between px and rem all of the time.

**Comment by tomgco** [comment]
> How would that work in practice for stuff other than font sizes? (like paddings and margins)

`rems` can be used for that and still use the font size as a base afaik.

**Comment by alex-windett** [comment]
>  implement <h1>, <h2>, <h3>, <h4>, <h5>, <p> and <small> and use that everywhere

I saw that there has been an `H1` react component created, but would it not make more sense to add the sizes and styles to global style sheet instead?

**Comment by ramitos** [comment]
the problem with global styles is that they take priority with styled components. 

Try to style something that is defined in `<Base>` (like an anchor) and override one of the rules. You'll see that you need to add an `!important`.

Ideally we should move everything out of <Base> into each component to avoid that

**Comment by alex-windett** [comment]
> Try to style something that is defined in <Base> (like an anchor) and override one of the rules. You'll see that you need to add an !important.

I did notice that, but it just seems a bit excessive to me to create components for such simple HTML elements.

**Comment by alex-windett** [comment]
Could this work - https://github.com/yldio/joyent-portal/commit/f2d66be58ee4dc73576a7a58d6ec01c286453f66

This way there is basically no nesting of base styles, so hopefully make that `!important` redundent to style H1s and things
