### ISSUE TITLE
05.01.17 Wireframe iterations based on feedback

### ISSUE THREAD

**Issue by luisklefsjo** [yldio/joyent-portal#148]
**05.01.17**
https://docs.google.com/a/make-us-proud.com/document/d/1ihUNjqgTzXZlXkwIObUDIE7ZKTCrY_QNCWiuDTLQZpg/edit?usp=sharing

**Comment by ajones5876** [comment]
Documented here: https://github.com/yldio/joyent-portal/wiki/User-Testing
