### ISSUE TITLE
Documentation decisions.

### ISSUE THREAD

**Issue by tomgco** [yldio/joyent-portal#15]
We have multiple levels of documentation that needs to occur in this project.

To list a few the following are some that are the most important for this project to be successful as an open-source project.
- ~~UI / UX design decisions~~
- ~~UI / UX usability guidelines~~
- ~~UI / UX technical interoperability guides~~
- Web Application architecture
- Web Application design decisions
- Dashboard development best practices (@tomgco)
- Dashboard overall architecture (ContainerPilot, API's, Databases?) - (@tomgco)
- Dashboard technology overview.
- Contribution Guidelines (@tomgco)

I would be great if I could get some feedback on this from @raoulmillais @ramitos @alex-windett and for the UI / UX documentation maybe @antonasdeduchovas and @luisklefsjo. 

I would also be helpful if you could mention the points which you wish to be a part of so I could update the bullet points with you names next to it to make it easier to split out at a later date, it is ok to have multiple people on one point.

When we have this information we can then decide on how best to structure each part of documentation in separate issues.

**Comment by ramitos** [comment]
no longer relevant
