### ISSUE TITLE
11.01.17_Workshop: Logs and Activity Feed

### ISSUE THREAD

**Issue by luisklefsjo** [yldio/joyent-portal#150]
**Workshop: Logs and Activity Feed**

https://docs.google.com/a/make-us-proud.com/document/d/1M6SZDjMKdaDUEb6YYOpCoMCKxidEbiOB-OAeQp18je4/edit?usp=sharing

**Comment by ajones5876** [comment]
Documented here: https://github.com/yldio/joyent-portal/issues/190
