### ISSUE TITLE
11.01.17_Workshop: Deployment Queue

### ISSUE THREAD

**Issue by luisklefsjo** [yldio/joyent-portal#152]
**Deployment Queue**

https://docs.google.com/a/make-us-proud.com/document/d/1erZYGL9dcjj3UnRJyxL9P5XblckIRD3eLQ2YRQ1ElN0/edit?usp=sharing

**Comment by ajones5876** [comment]
Documented here: https://github.com/yldio/joyent-portal/issues/220
