### ISSUE TITLE
Webpack font loader

### ISSUE THREAD

**Issue by alex-windett** [yldio/joyent-portal#160]
Something that I've come across in the past, should we be more specific in the path that is used in the this loader? When I've done this before, svg's that have been saved as assets have been picked up by the font loader as its looking for svg fonts.

https://github.com/yldio/joyent-portal/blob/4953ae36ea73f4a756fde7d7e8063d4e356078bf/frontend/webpack/base.js#L76

a bit of pseudo code 
path.join(UI, 'assets/fonts');

Not sure if its necessary, but something I noticed while looking at webpack config

**Comment by tomgco** [comment]
That is a great point, and actually something I am seeing already.
