### ISSUE TITLE
Allow people to deploy by writing and uploading a docker compose 

### ISSUE THREAD

**Issue by ajones5876** [yldio/joyent-portal#167]
## Problem Statement
Every project deployed on Triton is configured with a manifest file. It has been outlined that a user should be able to upload a previously written manifest file and also write a new manifest file in the browser to complete this task. When completing the latter, it is important that there are ample educational components so that a novice can complete the same task nearly as well as an expert.

## Persona
**[Nicola](https://github.com/yldio/joyent-portal/wiki/Persona-3:-Nicola-(The-Experienced-Early-Adopter))** (The Experienced Early Adopter):
- Experience: Very senior / CTO
- Specialisation: Fullstack, DevOps

## Latest Links (kept up to  date)
- Initial research: https://docs.google.com/a/make-us-proud.com/document/d/1W4B4w1nT7FO-bFBHCkRAn1MzTER8NE6GkZJ7EtE-Syc/edit?usp=sharing
- Sketches: https://drive.google.com/drive/folders/0Bw56g3tFwIuWLS01QTYzV3dveVE?usp=sharing
- Visual Design: https://drive.google.com/open?id=0B1oWObk56wa5SDBlQ1Y1cTJuQWc (out dated)
- Prototype: https://marvelapp.com/3jhbi8b/screen/26072593
- Testing: https://drive.google.com/open?id=1bSS67EAeNObldIJil3ZoUQEJFDGDsOKxI_mrLe57HSw

**Comment by ajones5876** [comment]
**Workshop**
Our resulting team sketches are here: https://drive.google.com/drive/folders/0Bw56g3tFwIuWLS01QTYzV3dveVE?usp=sharing

From these sketches we started to settle on a dropdown method of guiding people through creating their manifest file.

**Comment by ajones5876** [comment]
**Prototype**
A quick mockup of this idea in Sketch and imported into Marvel can be viewed here: https://marvelapp.com/3e30h56/screen/24262439

**Comment by ajones5876** [comment]
Upon discussions it was discussed that the current proposed solution is too complex. This design needs to be scaled back to a simpler linting process, very similar to the auto-complete features on sublime text.

**Comment by ajones5876** [comment]
**Prototype**
I created an improved prototype based off of the discussions from the last prototype:
https://marvelapp.com/2jegi07/screen/24429445

Sketch file here:
https://drive.google.com/a/make-us-proud.com/file/d/0Bw56g3tFwIuWOFdHS3VQZjQ3Y3M/view?usp=sharing

**Comment by ajones5876** [comment]
**Prototype**
https://marvelapp.com/ej9b136/screen/24489183

**Comment by ajones5876** [comment]
**Prototype**
New visual designs and prototype focus on a very simple educational component through comments (which can be turned off) as well as a yet designed accompanying documentation page.
https://marvelapp.com/1diddi3/screen/24947127

**Comment by ajones5876** [comment]
**Visual Design**
New designs incorporate a 'review page'
![image](https://cloud.githubusercontent.com/assets/7900773/23130944/28765222-f780-11e6-88bb-c89f36b419b9.png)

**Comment by ajones5876** [comment]
**New Prototype and Testing Results**
Prototype: https://marvelapp.com/3jhbi8b/screen/26072593
Testing: https://drive.google.com/open?id=1bSS67EAeNObldIJil3ZoUQEJFDGDsOKxI_mrLe57HSw

![image](https://cloud.githubusercontent.com/assets/7900773/24207438/b8a42072-0f18-11e7-8f88-0b6cf761a23e.png)
![image](https://cloud.githubusercontent.com/assets/7900773/24207448/c58006ee-0f18-11e7-9740-268f02a4ce35.png)

**Testing Results:**
- nearly every tester likened this to a Docker Compose file (which is completely correct)
- the comments were useful for people as well as the demo project
- not many testers collapsed the services
- the in line error detection proceed useful
- some internal discussions around more educational components have been discussed

**Comment by ramitos** [comment]
closing with:
 - https://github.com/yldio/joyent-portal/issues/485
 - https://github.com/yldio/joyent-portal/pull/524
 - https://github.com/yldio/joyent-portal/pull/514
 - https://github.com/yldio/joyent-portal/pull/494
