### ISSUE TITLE
Typo in Data-table component

### ISSUE THREAD

**Issue by tomgco** [yldio/joyent-portal#173]
Memeber -> Member

![tenor](https://cloud.githubusercontent.com/assets/524382/22335460/c0555b1e-e3d6-11e6-8acb-614241a7a394.gif)

https://github.com/yldio/joyent-portal/blob/fc9d940986f48e8e2e4c90810e969d9c188da5fb/ui/src/components/table-data-table/story.js#L20

https://github.com/yldio/joyent-portal/blame/fc9d940986f48e8e2e4c90810e969d9c188da5fb/ui/src/components/table-data-table/readme.md#L32

**Comment by ramitos** [comment]
no longer relevant
