### ISSUE TITLE
Personas

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#186]
**Finalised**
Confirmed personas: https://drive.google.com/open?id=0B03uff53G5KYUTUzRkJDZUp0akU

**Comment by ajones5876** [comment]
**Public**
Inputted personas into Wiki:
- Daniel: https://github.com/yldio/joyent-portal/wiki/Persona-1:-Daniel-(The-Cautious-Traditionalist)
- Jorge: https://github.com/yldio/joyent-portal/wiki/Persona-2:-Jorge-(The-Aware-Explorer)
- Nicola: https://github.com/yldio/joyent-portal/wiki/Persona-3:-Nicola-(The-Experienced-Early-Adopter)
- Jim: https://github.com/yldio/joyent-portal/wiki/Persona-4:-Jim-(The-Observing-Auditor)
