### ISSUE TITLE
Workshop 6: What might go Dashboards?

### ISSUE THREAD

**Issue by luisklefsjo** [yldio/joyent-portal#19]
What might go on the Dashboard? (Initial assumptions)
https://docs.google.com/document/d/1whUTDkkBGCKtZAXMbR7paULafKzwzE3HyvOjUr3JIHw/edit?usp=sharing

**Comment by ajones5876** [comment]
Documented here: https://github.com/yldio/joyent-portal/wiki/13.10.16:-What-might-go-on-the-dashboards%3F
