### ISSUE TITLE
Allow people to roll back, update and manage the versions of their project

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#191]
## Problem Statement
If a user is alerted of a problem in their application, rolling back to a previous 'known to be working version' is a quick way to rectify this problem.

## Persona
**[Jorge](https://github.com/yldio/joyent-portal/wiki/Persona-2:-Jorge-(The-Aware-Explorer))** (The Aware Explorer)
- Experience: Mid level
- Specialisation: Fullstack

## Latest Links (kept up to  date)
Workshop Sketches: https://drive.google.com/open?id=0Bw56g3tFwIuWM1BtSF8zcDJseXc
Master Sketches: https://drive.google.com/open?id=0Bw56g3tFwIuWbjFOcVN3X0txTFk
Wireframes: https://drive.google.com/open?id=0Bw56g3tFwIuWQWowTnhpaHh4YXM (out dated)
Prototype: https://marvelapp.com/26i1f1a/screen/26761218
Test Results: https://docs.google.com/document/d/165agJVUiNxIkk90wDEZhYNBR8WoQpE7v1WdBneklqAU/edit (out dated)

**Comment by ajones5876** [comment]
**Testing**
- [ ] Be super explicit about state changes
- [ ] Explain what will happen to data 
- [ ] Consider creating a new version from a copy of an older one
- [ ] Provide a detailed instruction
- [ ] Swap position of the rollback dif

- Question: @tomgco @juditgreskovits if I rollback the whole project, does the whole app reprovision or only those services that have changed? Would that therefor make my application inaccessible?

**Comment by ajones5876** [comment]
**New Prototype**
- Prototype: https://invis.io/XNAXLWHAS#/224515647_Versions_1-1

This new design puts the versions in a list view and forces the user to click on each version in question to rollback too

**Comment by ajones5876** [comment]
**Sketching Workshop**
Sketches viewable here: https://drive.google.com/open?id=0Bw56g3tFwIuWM1BtSF8zcDJseXc

**Comment by ajones5876** [comment]
**Wireframes:**
https://drive.google.com/open?id=0Bw56g3tFwIuWQWowTnhpaHh4YXM

![image](https://cloud.githubusercontent.com/assets/7900773/24512455/8a604462-1566-11e7-9b02-ef5fd83404ff.png)

![image](https://cloud.githubusercontent.com/assets/7900773/24512471/93c01be0-1566-11e7-8d5b-38099b1c5c44.png)

![image](https://cloud.githubusercontent.com/assets/7900773/24512486/9dc79514-1566-11e7-9b58-7cf3aa0f783d.png)

![image](https://cloud.githubusercontent.com/assets/7900773/24512506/a889591a-1566-11e7-81e2-a254ec84d4a0.png)

![image](https://cloud.githubusercontent.com/assets/7900773/24512541/bdd2ce5a-1566-11e7-90b5-8573fe3a6699.png)

![image](https://cloud.githubusercontent.com/assets/7900773/24512552/c8531614-1566-11e7-9e66-540b0cff6106.png)

**Comment by ajones5876** [comment]
New prototype: https://marvelapp.com/26i1f1a/screen/26761218
