### ISSUE TITLE
Allow people to add/deploy unmanaged instances

### ISSUE THREAD

**Issue by ajones5876** [yldio/joyent-portal#197]
## Problem Statement
Although the current organisational principles of Joyent are Project -> Service -> Instance, in legacy there are just instances. It is expected that users will still want this ability to deploy unmanaged instances in relation to this legacy model. The Triton portal needs to provide a way for the user to do this.

## Persona
All

## Latest Links (kept up to  date)
Research: https://docs.google.com/document/d/1rvBSzsJX4T_lxvmjLFlz8HCC8OIcdjmqHpIFFROR6AY/edit?usp=sharing
Workshop Sketches: N/A
Visual Design: N/A
Prototype: N/A
Test Results: N/A

**Comment by antonasdeduchovas** [comment]
@ajones5876 correct me if i'm wrong, but an instance cannot be scaled - it can be added, provisioned, started, stopped, deleted. It's a singular entity. Only a service can be scaled, as it is a collection of instances. 

I believe we need to change phrasing for this issue to 'Adding instances'

**Comment by ajones5876** [comment]
@antonasdeduchovas changed the title
