### ISSUE TITLE
Allow users to see educational components (Taxonomy and Navigation)

### ISSUE THREAD

**Issue by ajones5876** [yldio/joyent-portal#198]
## Problem Statement
Educational components are vital for a user to understand their system

## Persona
All

## Latest Links (kept up to  date)
Workshop Sketches: N/A
Visual Design: https://drive.google.com/open?id=0B1oWObk56wa5SDBlQ1Y1cTJuQWc
Prototype: https://marvelapp.com/ej9b136/screen/24489183
Test Results: N/A

**Comment by antonasdeduchovas** [comment]
@ajones5876 I'd suggest avoid using word 'application'. Services within a project do not necessarily represent an application

**Comment by ajones5876** [comment]
@antonasdeduchovas changed!
