### ISSUE TITLE
Allow users to join and leave teams (RBAC)

### ISSUE THREAD

**Issue by ajones5876** [yldio/joyent-portal#210]
## Problem Statement
To be defined.

## Persona
**[Nicola](https://github.com/yldio/joyent-portal/wiki/Persona-3:-Nicola-(The-Experienced-Early-Adopter))** (The Experienced Early Adopter):
- Experience: Very senior / CTO
- Specialisation: Fullstack, DevOps

## Latest Links (kept up to  date)
- Initial research: https://docs.google.com/a/make-us-proud.com/document/d/1W4B4w1nT7FO-bFBHCkRAn1MzTER8NE6GkZJ7EtE-Syc/edit?usp=sharing
- Workshop Sketches: N/A
- Visual Design: https://drive.google.com/open?id=0B1oWObk56wa5SDBlQ1Y1cTJuQWc
- Prototype: https://marvelapp.com/ej9b136/screen/24489183
- Test Results: https://docs.google.com/document/d/165agJVUiNxIkk90wDEZhYNBR8WoQpE7v1WdBneklqAU/edit?usp=sharing

**Comment by ajones5876** [comment]
**Workshop**
October 19th, 2016

Luis, Antonas, Alex and Tom have been discussing about adding the concept of teams to the RBACv2 specification and to the new Joyent Cloud UI.

Questions:
- Do we need to consider teams as part of the proposed Joyent structure?
- What would the benefits be?
- How would they fit into the ecosystem?  

Pros:
- Logical grouping of people
- Makes it easier for simple users and teams to assign roles for multiple projects.
- Easy to add people to new projects.
- Giving policies to a group of people at one time instead of adding to each member.
- Mass assigning people to projects
-

Cons:
- Operational Complexity
- Adding more moving parts can cause complexity for a user to manage teams effectively, a lot of cloud platforms do not have teams due to the fact that they are pretty much only using the platform as a team, or as a solo actor. (auditor, for analytics, etc).
- Removing users from a project, but not from a team.
- Say that we have three projects and one team is assigned to all three projects. If a member of the team is removed from a project, it becomes very difficult to represent this within the RBACv2 specification.


**The team concluded that:**
Based on this, the team decided to put “teams” on pause for the being as we didn’t believe that the benefits are greater than the  complications it would mean from a technical perspective.

We also believe that we can always add “team” at a later stage quite easily, should this, further down the line, be deemed as something worth doing.

**Comment by ajones5876** [comment]
@alex-windett are you working on creating a front end for this?

**Comment by alex-windett** [comment]
Not as yet. Teams are still a concept and nothing has been designed/tested/prototyped. It would also need to be something we bring up with Joyent themselves and ask for an RFD. The functionality of teams would require work from their technical team as well as ours.

At the moment the only reference is:

> belong to multiple organizations and multiple project teams.

can be found [here](https://github.com/joyent/rfd/blob/master/rfd/0013/README.md#introduction).

This is what we see as a project, a "team" would be a collection of people who all have membership to an organisation or project that have differing

**Comment by ajones5876** [comment]
Prototype: https://marvelapp.com/1hbcc2d/screen/17413900

Test Results: https://docs.google.com/document/d/165agJVUiNxIkk90wDEZhYNBR8WoQpE7v1WdBneklqAU/edit?usp=sharing
- You should be able to assign a role while you’re inviting people
- Consider how invitation suggestions work: are these are the people already in the organisation or Joyent users in general?
- Can people be added when setting up metrics alerts?
