### ISSUE TITLE
Mobile adaptions: UI, UX and Technical

### ISSUE THREAD

**Issue by ajones5876** [yldio/joyent-portal#217]
@antonasdeduchovas: Mobile adaptions for the UI, UX need to be created and shared.

**Comment by ajones5876** [comment]
@juditgreskovits and @alex-windett: we need to come up with a list of elements that won't work on mobile. I'm thinking that at the moment this _could_ include the force move graph for the topology.

**Comment by alex-windett** [comment]
I think everything we have is easy to transfer after to mobile. However, two things spring to mind

- The topology view will become very very clustered. 
- With metrics , instance lists and service lists we are dealing with a potentially huge amount of live data so that's going to eat away at people's data and a devuces' CPU

**Comment by alex-windett** [comment]
Can't edit comments on mobile. Should read *transfer to mobile* instead of *transfer to after mobile*

**Comment by ajones5876** [comment]
- redesigning the topology for mobile completely makes sense
- having no metrics on mobile is going to be an issue, perhaps we show very high level indicators e.g. healthy/not healthy and then an option to see metrics for specific services/instances

**Comment by AnthonyMann** [comment]
Disagree that detailed metrics aren't doable on mobile. I would expect them to be integral to visualising service issues, which are likely to happen when you're not in the office.

Data usage shouldn't be a big issue for our target demographic, I would generally expect them to have more modern mobile technology than the average consumer. We can check with our test audience.

**Comment by alex-windett** [comment]
Maybe doable was the wrong word. But everything can be converted to a mobile device but those two things I believe need considering

**Comment by ajones5876** [comment]
Tabs on mobile also need to be considered (just marking this from the previous discussion on Slack)

**Comment by ajones5876** [comment]
Merging this with the appropriate narrative on the narrative's board: https://github.com/yldio/joyent-portal/issues/250
