### ISSUE TITLE
Allow people to setup and receive alerts on their application

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#224]
## Goal
Allow people to receive alerts on their application

## Persona
**[Nicola](https://github.com/yldio/joyent-portal/wiki/Persona-3:-Nicola-(The-Experienced-Early-Adopter))** (The Experienced Early Adopter):
- Experience: Very senior / CTO
- Specialisation: Fullstack, DevOps

## Latest Links (kept up to  date)
- Initial research: https://docs.google.com/document/d/1M_lDFzTZSZ-dnP2Z3a8EnoC77qwGZI9zI-ScmEoEibs/edit & https://docs.google.com/document/d/1Mcu4_eTetltFQZzG_0maOBVsEK4OByA4E_GxCYBrdIE/edit
- Workshop Sketches: N/A
- Visual Design: https://drive.google.com/file/d/0B1oWObk56wa5SFNNSFh3UTRTdk0/view?usp=sharing
- Prototype: Project Overview: https://marvelapp.com/89id42e/screen/27709142, List View: https://marvelapp.com/5d5g751/screen/27709711, Header callout: https://marvelapp.com/28b1h8a/screen/27710543
- Test Results: https://docs.google.com/document/d/165agJVUiNxIkk90wDEZhYNBR8WoQpE7v1WdBneklqAU/edit (Out dated)

**Comment by ajones5876** [comment]
**Visual Design**
https://drive.google.com/file/d/0B1oWObk56wa5SFNNSFh3UTRTdk0/view?usp=sharing

**Prototype**
https://marvelapp.com/1hbcc2d/screen/17413892

**Test Results**
Doc here: https://docs.google.com/document/d/165agJVUiNxIkk90wDEZhYNBR8WoQpE7v1WdBneklqAU/edit
- Provide a clear explanation of what metrics / monitors / alerts are and provide an insight of what’s happening ‘under the hood’
- Explore how setting up the alerts can be more clear, more inviting (maybe an educational component?)
- Can people be added when setting up metrics alerts?

**Comment by ajones5876** [comment]
Research: https://docs.google.com/document/d/1Mcu4_eTetltFQZzG_0maOBVsEK4OByA4E_GxCYBrdIE/edit

**Comment by ajones5876** [comment]
**New Prototypes:**
- Project Overview: https://marvelapp.com/89id42e/screen/27709142
