### ISSUE TITLE
Open sourcing

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#225]
Discussion started here before migrations of boards: https://github.com/yldio/joyent-portal/issues/203

**Comment by ajones5876** [comment]
The main issue we have at the moment with open sourcing is the GitHub wiki is not sufficient for our documentation:
- Two people cannot work on it at the same time limiting it’s use in meetings
- Formatting is bad making it more difficult to communicate content (especially to people unfamiliar with markdown)
- Pushing the wiki via git is infeasible for growing design community
- No stats on page views

Possible solutions:
* Link to open Google Drive folder for meetings like so: https://github.com/yldio/joyent-portal/wiki/Meetings
 * 


- Open, editable Googl
