### ISSUE TITLE
Let us talk about metrics

### ISSUE THREAD

**Issue by tomgco** [yldio/joyent-portal#24]
**Initial task**
Learn how we can create Insights and Intelligent Suggestions based on performance metrics.

..............

A few places for inspiration:

Data Dog - https://www.datadoghq.com/dashboarding/
New Relic - https://newrelic.com/application-monitoring
Sysdig Cloud - https://sysdig.com/product/
Prometheus (required by container pilot) - https://prometheus.io/

**Comment by ajones5876** [comment]
Merged with: https://github.com/yldio/joyent-portal/issues/212
