### ISSUE TITLE
Allow users to use the application effectively on Mobile

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#250]
## Problem Statement
Users should be able to complete most (if not all actions) on a mobile device with a low bandwidth connection

## Persona
All

## Latest Links (kept up to  date)
Prototype: https://marvelapp.com/7h30954/screen/25648604

**Comment by ajones5876** [comment]
@antonasdeduchovas and @alex-windett could you please comment the work you have done on this narrative please. Thanks!

**Comment by ajones5876** [comment]
Initial discussions here: https://github.com/yldio/joyent-portal/issues/217

**Comment by ajones5876** [comment]
**Prototype**:https://marvelapp.com/7h30954/screen/25648604
