### ISSUE TITLE
Allow users to add services from a container pilot catalogue

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#253]
## Problem Statement
In Alpha, the only way for a user to add services was by editing or uploading a new project manifest. However, changing a manifest requires an in depth technical knowledge. In Beta, we want to make this process easier by providing a container pilot catalogue (a library of services) that a user can use to easily add services to begin scaffolding their application.

## Persona
All

## Latest Links (kept up to  date)
- Initial research: https://drive.google.com/drive/u/0/folders/0Bw56g3tFwIuWLUZlUWhzTzItNm8
- Workshop Sketches: N/A
- Visual Design: N/A
- Test Results: N/A

**Comment by ajones5876** [comment]
Initial research conducted here: https://github.com/yldio/joyent-portal/issues/169

**Comment by ajones5876** [comment]
**Workshop**
https://docs.google.com/document/d/1dXpWHD9tszgdI28dx-WjZomGj8uaxCf158sjfvTiSPw/edit

**Comment by ajones5876** [comment]
**Sketches**
https://drive.google.com/drive/u/0/folders/0Bw56g3tFwIuWLTdPOWlqNkt1MWc

**Comment by ajones5876** [comment]
**Consolidated Sketch**
https://drive.google.com/drive/u/0/folders/0Bw56g3tFwIuWeERhd3hUWV82V3M

**Comment by ajones5876** [comment]
**Sketch File**
https://drive.google.com/open?id=0Bw56g3tFwIuWekJzOWZSZ0NGUmM

**Comment by ajones5876** [comment]
**Prototypes**
https://marvelapp.com/1j934e6 and https://marvelapp.com/48g1363/screen/28964557

**Comment by ajones5876** [comment]
**New Prototype**
https://marvelapp.com/3b2e4i1/screen/29008792
