### ISSUE TITLE
Allow users to deploy their application with Git

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#258]
## Problem Statement
The user should be able to deploy via git whenever they make a code change to their application. The user will beed a URL to paste into their terminal to achieve this. 

## Persona
To be defined

## Latest Links (kept up to  date)
- Initial research: N/A
- Workshop Sketches: N/A
- Visual Design: N/A
- Test Results: N/A

**Comment by ajones5876** [comment]
@ramitos when deploying via git, will the user do this on a project or service level?

**Comment by alex-windett** [comment]
> @ramitos when deploying via git, will the user do this on a project or service level?

I initially thought a service would be the more conventional, but then thought some people could have entire projects under a single Git directory. But needed clarification for me
