### ISSUE TITLE
add icons to ui [#208]

### ISSUE THREAD

**Issue by ramitos** [yldio/joyent-portal#282]
can they be SVG?

Google Drive Folder: https://drive.google.com/drive/folders/0B1oWObk56wa5T01fRTJEU1NUWjg

*Naming Rule*
If there are different variants of the same icon try and use BEM style file name

e.g

[name]-[varient]-[style].svg

notification-warning.svg
notification-warning-inverted.svg

#208

**Comment by alex-windett** [comment]
@antonasdeduchovas When you have time, would you be able to let us  know which of the icons are ready to go into build - I think you said a while back that they may need some updating

**Comment by alex-windett** [comment]
@yldio/joyent-technical Icons can be added to the frontend - they may change, but the sizes wont. Will export them as SVG as add them to a google drive folder for use
