### ISSUE TITLE
Workshop 7: Teams

### ISSUE THREAD

**Issue by luisklefsjo** [yldio/joyent-portal#31]
Teams
https://docs.google.com/document/d/18gUlu4TiufQPJkKUFktHWucwqO0rvXUFhIepRBP4Qnk/edit#heading=h.xzdrzjgbsrz2

**Comment by ajones5876** [comment]
Documented here: https://github.com/yldio/joyent-portal/wiki/21.10.16:-Adding-teams-to-Role-Back-Action-Control-(RBAC)
