### ISSUE TITLE
Move tests to run in pre-built Docker Containers

### ISSUE THREAD

**Issue by tomgco** [yldio/joyent-portal#33]
Using `docker run <hash> make install test`

This functionality already exists, just yet to be implemented, this ideally means we can cache the dependencies needed and speed up build times. (If circleci supported this)
Never-the-less this is still good practise as we are testing the code in the environment where the code will be deployed. (minus development / production module mishapes).

**Comment by ramitos** [comment]
no longer relevant for my-joy-beta
