### ISSUE TITLE
Workshop 8: Abstracts and Quick Actions

### ISSUE THREAD

**Issue by luisklefsjo** [yldio/joyent-portal#41]
https://docs.google.com/a/make-us-proud.com/document/d/1PPhnygOzxNc6RD-JmfetNFWswnmLn9rjA0fM0eL3-XU/edit?usp=sharing

**Comment by ajones5876** [comment]
Documented here: https://github.com/yldio/joyent-portal/wiki/27.10.16:-Abstracts-and-Quick-Actions
