### ISSUE TITLE
Allow a user's experience in the CLI to mirror and complement what they experience in the UI

### ISSUE THREAD

**Issue by ajones5876** [yldio/joyent-portal#411]
## Problem Statement
In Alpha, the only way for a user to add services and compose applications was by editing or uploading a new project manifest. In Beta, we want to make this process easier by providing a container pilot catalogue (a library of services) that a user can use to easily add services to begin scaffolding their application.

## Persona
To Be Defined (Technical)

**Comment by ajones5876** [comment]
**Initial Research**
In this doc I outline the steps someone would go through when deploying the [Wordpress Autopilot Pattern](https://github.com/autopilotpattern/wordpress) example: https://docs.google.com/a/make-us-proud.com/document/d/1vQBdsR9-2DM742oo82KlMlMYhtsXiCeelycec9tGdxg/edit?usp=sharing

My key findings were:
- It's very difficult to configure the CLI. You have to install Triton and Docker, get them to work together, and I had to do some serious searching (outside of the documentation provided in the tutorial) to get this to work.
- Comparing the above with installing the CLI with something like [Ionic](http://ionicframework.com/getting-started/) and this CLI configuration seems incredibly cumbersome. [Heroku also has a one line install (for OSX) for their CLI.](https://devcenter.heroku.com/articles/heroku-cli) 
- When I inputted by Manta details the steps were as follows: I had to create the bucket on the UI, then go to my text editor to input the details and then finally upload via the CLI. Theoretically, I imagine this could all be done in the CLI.
- It took an *extremely* long time to deploy the application and scale. There was no progress indicator in the CLI so I honestly wondered after ten minutes if I had made a mistake or not.

In light of going through this, I definitely think there should be an option when creating a project to do this via the CLI, and not just in the UI. Should this be in Alpha?

**Comment by AnthonyMann** [comment]
@ajones5876 see the RFD here which covers the proposed CLI env for Mariposa - https://github.com/joyent/rfd/blob/master/rfd/0036/projects/triton-cli.md
