### ISSUE TITLE
Allow users to view project level metrics

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#434]
## Problem Statement
A user should have a place in the application that they can setup and view project level metrics

## Persona
All

## Latest Links (kept up to  date)
Initial research: https://docs.google.com/document/d/1Mcu4_eTetltFQZzG_0maOB
Workshop Sketches: N/A
Wireframes:
Prototype: https://marvelapp.com/1hf4eh1/screen/27708179 & https://marvelapp.com/1hf4eh1/screen/27708179

**Comment by ajones5876** [comment]
Project Overview prototype small screens: https://marvelapp.com/1hf4eh1/screen/27708179

Project Overview prototype large screens: https://marvelapp.com/5d5efg7/screen/27708796
