### ISSUE TITLE
Expose the metadata about each deployment-group gathered through polling to Triton and ContainerPilot

### ISSUE THREAD

**Issue by ajones5876** [yldio/joyent-portal#443]
technically difficult, design unrelated

**Comment by ajones5876** [comment]
@ramitos @juditgreskovits @geek  is this narrative in progress? And also would you be able to update the description above?

**Comment by geek** [comment]
@ajones5876 this is not in progress at the moment.

**Comment by ajones5876** [comment]
Thanks @geek, I think @juditgreskovits has done a tonne of work on this though right?
