### ISSUE TITLE
Implement base UI components

### ISSUE THREAD

**Issue by ramitos** [yldio/joyent-portal#45]
- [x] `<Input />` #44 
 - [x] `<Select />` #48
 - [x] `<RangeSlider />` https://github.com/yldio/joyent-portal/commit/0b332cbeb6621c99745fc5453e7716b478d56e7b
 - [x] `<Pagination />` #54
 - [x] `<Icon />` https://github.com/yldio/joyent-portal/commit/0bb2b495a73902bc6e0fba7d979f1644b0fe1f5b
 - [x] `<Button />` with `<Icon />`
 - [x] `<Alert />` https://github.com/yldio/joyent-portal/commit/bce2e8fc01f6e42fe946f9bb2e3a2bbcf6decace
 - [x] `<Modal />`  https://github.com/yldio/joyent-portal/commit/9e0193de7dbcd284b65445ed3cc41e1dc9d7168b

**Comment by alex-windett** [comment]
Was looking over Antonas updated UI Sketch file, and there are a couple of components which would be good to talk over before we build them. First, there is the fuzzy search on things like adding people to teams by email / name. There is also how we are going to do custom accessable option selects.

**Comment by tomgco** [comment]
> Was looking over Antonas updated UI Sketch file, and there are a couple of components which would be good to talk over before we build them. First, there is the fuzzy search on things like adding people to teams by email / name. There is also how we are going to do custom accessable option selects.

As these seem like big components, maybe it will be worth just opening an issue for each one?

**Comment by alex-windett** [comment]
Fuzzy Search - https://github.com/yldio/joyent-portal/issues/128
Dropdown Select - https://github.com/yldio/joyent-portal/issues/129
