### ISSUE TITLE
Create designs for dashboard alpha

### ISSUE THREAD

**Issue by juditgreskovits** [yldio/joyent-portal#455]

**Comment by juditgreskovits** [comment]
*** where to show datacenter? on service or in header or elsewhere? topology and list implications *** 
*** bulk actions? *** 
*** discuss / review instance list designs *** 
- Header to contain only logo and username w/o interaction (no avatar, no dropdown)
- Remove org tabs 
- Home page is Deployment Groups list - need revision of layout
- Deployment Group menu to contain only: Services, Instances and Manifest
- Services Topology: no metrics display
- QuickMenu actions: scale, start, restart, stop, delete
- Services List: no metrics (leave space?)
- Service menu to contain only: Instances

- Create Deployment Group w/o package selection

**Comment by antonasdeduchovas** [comment]
I've uploaded the new revised you to Zeplin. I haven't documented all of the changes yet - I'd like to leave it for later time. Please let me know if you need it.

The only major changes that everyone needs to be aware of are:
- paragraph text size changed from 16 to 15
- Paragraph title size is 15
- Page title size is 24, weight - regular (used to be semibold)
- button text labels are 15
- text fields have changed their style - default style of an input field title is 13, semibold

Text has two new main colours: dark grey (used for majority of copy) - #494949 and light grey - for inactive of low-priority content - #808080. These changed were made to improve contrast between text and the background. All of the dark grey icons have a new colour - #494949, same as text.

All of these changed are illustrated in the new mockups. There are some spacing changes, which I will document as soon as possible.

Let me know what you think @juditgreskovits @ramitos

**Comment by ramitos** [comment]
Great work @antonasdeduchovas 👏
