### ISSUE TITLE
Add tooltips to Instance List Health statuses and statuses

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#594]

**Comment by XanderJones93** [comment]
HEALTH
Health = Your instance is operating as expected
Unhealthy = Your instance is not operating as expected
Maintenance = You've set your instance to this manually, use the Container Pilot CLI to change
Unknown = We've connected to your instance but we have no health information
Unavailable = We cannot connect to your instance

INSTANCE STATUS
Running = Your instance is operating
Provisioning = Your instance is downloading dependencies and compiling
Ready = Your instance finished provisioning and is ready to be run, it'll be running soon
Stopping = Your instance is going to be stopped soon
Stopped = Your instance isn't doing anything, you can start it
Offline = We have no idea what this means, do you??????
Failed = Your instance has crashed
Unknown = We cannot work out what status your instance is in
