### ISSUE TITLE
Create Object Map for Triton Public Cloud

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#647]
Research on creating Object Maps: https://docs.google.com/document/d/1aM7xkwZ7knqks0dCGoMYwI6w7t5u2y16hDkoR8ChdeY/edit

G Drive Folder with existing object maps in: https://drive.google.com/drive/folders/0Bw56g3tFwIuWRG1oclV0UDAzTFE?usp=sharing

G Drive for workshops: https://drive.google.com/open?id=0Bw56g3tFwIuWRG1oclV0UDAzTFE

**Comment by AlexJupiter** [comment]
Background reading on creating objects maps: 
https://alistapart.com/article/ooux-a-foundation-for-interaction-design
https://alistapart.com/article/object-oriented-ux

**Comment by AlexJupiter** [comment]
@yaili can you upload the post it notes of the object map creation here please?

**Comment by AlexJupiter** [comment]
Figma file with Object Map: https://www.figma.com/file/HZ4Hk35VrqetghMiM5tWsjKV/Object-Map

To Do:
- [ ] Prioritise CTAs
- [ ] Clarify with Casey

**Comment by yaili** [comment]
I only just saw this.

They are here: https://drive.google.com/drive/u/1/folders/0Bw56g3tFwIuWLU9meHl2SG5MSW8
