### ISSUE TITLE
Technical Prototype of Package Selection

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#650]
Marvel prototype here: https://marvelapp.com/35bj0jb (just the package selection needs to be prototyped).

Casey originally mentioned that we could just use a JSON file to mock the data up.

**Comment by AlexJupiter** [comment]
**Clarification on Ticket**
The goal of this ticket is to create a technical prototype around package selection for instance creation. The rest of the instance creation epic can be prototyped using Figma/Marvel, however the method of interactions for our current designs for package selection cannot be prototyped in this method (specifically the sliding range bars).

This technical prototype will be presented to users in testing sessions to elicit feedback (approximately at the end of September). Our aim is to increase our confidence in this design through these testing sessions. If the testing subjects can easily choose a package with this technical prototype this means that our design is going in the correct direction (we will have more specific Key Performance Indicators clarified before the testing session).

The package selection should follow the user journey of Jorge, as defined [here](https://drive.google.com/open?id=0B1oWObk56wa5SmVWeUplWHRDVXc), and so should only include data for selecting the packages of image Ubuntu 16.04.

The Figma file for this technical prototype is [here](https://www.figma.com/file/KBRlarmASWjwBWvCrP2WvA/Create-instance-Package-Selection-Technical-Prototype).

A Marvel prototype showing the expected interactions (minus the sliding range bars) is [here](https://marvelapp.com/6bg90ce/screen/32266322).
 
Tasks for design team:
- [ ] Name patterns 
- [ ] Create steps for the sliding range bars

**Comment by yaili** [comment]
Here are the steps for the sliding range bars:

**GB RAM:**
- 0.256 GB
- 0.768 GB
- 1.8 GB
- 3.8 GB
- 7.8 GB
- 15.8 GB
- 31.8 GB
- 63.8 GB

**vCPUs:**
- 0.25
- 0.5
- 1
- 2
- 4
- 8

**TB Disk:**
- 0.01
- 0.025
- 0.05
- 0.1
- 0.2
- 0.4
- 0.8
- 1.2
- 1.6
- 2.4
- 4.9

**$/hr:**
- 0.016
- 0.033
- 0.066
- 0.084
- 0.131
- 0.166
- 0.259
- 0.263
- 0.333
- 0.413
- 0.52
- 0.525
- 0.665
- 0.825
- 1.039
- 1.066
- 1.725
- 2.131

**Comment by AlexJupiter** [comment]
@SaraVieira after initial testing sessions, as we discussed these improvements should be put into the technical prototype:
- [ ]  SSD/Mag options (storage optimised will be Mag)
- [ ]  Sort by price
- [ ]  Clicking the top button filters, will adjust the sliding filters

**Comment by AlexJupiter** [comment]
@SaraVieira just clarifying our conversations from earlier:

1.) When I click the quick filter "Storage Optimised" I am expecting the sliders to change:
![image](https://user-images.githubusercontent.com/7900773/30706659-fe5db16a-9ef0-11e7-91eb-0ec1a8bef3d2.png)
(which they do, awesome)

2.) Now, I'm going to adjust the slider so I only have one package:
![image](https://user-images.githubusercontent.com/7900773/30706825-83998520-9ef1-11e7-99e8-c5d7d83c3b95.png)
(works as expected, awesome)

3.) Now, I'm going to unclick "Storage Optimized" 
![image](https://user-images.githubusercontent.com/7900773/30706897-b3f22c4a-9ef1-11e7-91b3-7d79a2a3282d.png)
Here I would expect the sliders to stay in the same place. Which they don't. Needs to be fixed :).

- [ ]  Done
