### ISSUE TITLE
UI Review

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#651]
Implement these UI improvements to CoPilot: https://docs.google.com/document/d/1WneBNcEiPa5niqkcF4QOg8ujJKoz_SHG3oaJUkWPHNk/edit

**Comment by SaraVieira** [comment]
@alexJupiter I already created a bunch of tickets for these divided by pages

**Comment by yaili** [comment]
@SaraVieira @AlexJupiter does that mean we can close this, or make it an epic with the other issues inside?

**Comment by AlexJupiter** [comment]
Yep - I believe this can be closed (but I wanna check with Sara first), we have an apic for this here: https://github.com/yldio/joyent-portal/issues/700 Make sure ZenHub is installed!

**Comment by SaraVieira** [comment]
We can close   this has been divided and has an epic now
