### ISSUE TITLE
Saving a draft and creating a ticket (increasing provisioning)

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#660]

**Comment by AlexJupiter** [comment]
Are we designing the ticket portal as well?

**Comment by AlexJupiter** [comment]
Engineering estimate: 40+ (this is a big unknown)

**Comment by yaili** [comment]
@AlexJupiter I think the answer was **no**, right?

**Comment by AlexJupiter** [comment]
@yaili Yep, definitely a no! :)
