### ISSUE TITLE
gen-keys.sh - open?

### ISSUE THREAD

**Issue by neuroserve** [yldio/joyent-portal#663]
The gen-keys.sh bash-script ends with the following three lines:

open $keys_path/client.p12 &
echo
echo "You can complete setup by running './setup.sh ~/path/to/TRITON_PRIVATE_KEY $keys_path/ca.crt $keys_path/server.key $keys_path/server.crt'"

"open $keys_path/client.p12 &" generates an error. 
Is that a typo?

**Comment by ramitos** [comment]
`open` is a macOS cmd.

> The ooppeenn command opens a file (or a directory or URL), just as if you had double-clicked the file's icon. If no application name is specified, the default application as determined via LaunchServices is used to open the specified files.

**Comment by neuroserve** [comment]
Oh - didn't know, that this was macOs only.

**Comment by ramitos** [comment]
The project is not macOS only. This script is. But what that line is does, is add the certificate to the keychain so that the browsers trust it.
