### ISSUE TITLE
prometheus config - fixed "triton.zone"

### ISSUE THREAD

**Issue by neuroserve** [yldio/joyent-portal#664]
prometheus.yml.ctmpl contains
     triton_sd_configs:
      - account: '{{env "TRITON_ACCOUNT"}}'
        dns_suffix: 'cmon.{{env "TRITON_DC"}}.triton.zone'
        endpoint: 'cmon.{{env "TRITON_DC"}}.triton.zone'

I'm working against a local triton installation - but that probably won't work against Triton public cloud. We need to get that from the environment or from user input.

**Comment by geek** [comment]
@neuroserve those environment variables are populated from the generated `_env` file. You will need to run `./setup.sh` to have the file created.

**Comment by neuroserve** [comment]
I have done that. But my Triton installation is not in the Joyent Public Cloud and therefore uses a different tld. Isn't there a way to be more generic? I'm not sure, but my Triton profile includes the tld, too.

**Comment by geek** [comment]
@neuroserve I will try this out locally with CoaL... we have mainly been targeting the hosted triton solution from Joyent.... I'll report back

**Comment by neuroserve** [comment]
in setup.sh TRITON_DC is set here:
TRITON_DC=$(triton profile get | awk -F"/" '/url:/{print $3}' | awk -F'.' '{print $1}')
In my case this produces "cloudapi" (which is the triton-api endpoint in my setup).
I don't know, whether it is possible to obtain the complete cmon-endpoint name from the triton profile or from the triton-api endpoint (afaik it is possible to get the docker-endpoint name that way).
I understand, that cmon in the Joyent cloud is in the "triton.zone" and that is probably different from the domain of the cloudapi domain - thus it makes sense in a way to set the "triton.zone" domain statically in prometheus' config file. But it would be nice, if the complete name of the cmon-endpoint would be variable (e. g. if Joyent decides to change the name of the cmon endpoint domain).

**Comment by ramitos** [comment]
no longer relevant
