### ISSUE TITLE
detach some packages

### ISSUE THREAD

**Issue by ramitos** [yldio/joyent-portal#677]
CoPilot repo: 
 - [ ] cp-frontend
 - [ ] docker-compose-client
 - [ ] cp-gql-mock-server
 - [ ] cp-gql-schema
 - [ ] cp-rdb-bootstrap (remove)
 - [ ] portal-api

Detach or donate
 - [ ] normalized-styled-components
 - [ ] remcalc
 - [ ] rnd-id
 - [ ] styled-is
 - [ ] unitcalc
 - [ ] pseudo-json-ast
 - [ ] pseudo-yaml-ast

@geek:
 - can we move CoPilot to https://github.com/yldio/copilot ?
 - if we don't donate those styling packages, should they belong to @yldio or @joyent ?
 - if the styled-components team wants the styling packages, can we donate them? (we still use them and will continue using them)
 - can we make the docker-compose-api repo public?

**Comment by geek** [comment]
> can we move CoPilot to https://github.com/yldio/copilot ?
Yes, good idea.

> can we make the docker-compose-api repo public?
Yes, we should... it doesn't have any secrets or secret history from what I saw.

**Comment by ramitos** [comment]
done: 
 - [yldio/joyent-portal](https://github.com/yldio/joyent-portal/tree/master/packages)
 - [yldio/styled-is](https://github.com/yldio/styled-is)
 - [yldio/copilot](https://github.com/yldio/copilot/tree/master/packages)
 - [yldio/joyent-manifest-editor](https://github.com/yldio/joyent-manifest-editor)
 - [yldio/unitcalc](https://github.com/yldio/unitcalc)
 - [yldio/stylelint-config-joyent-portal](https://github.com/yldio/stylelint-config-joyent-portal)
 - [yldio/normalized-styled-components](https://github.com/yldio/normalized-styled-components)
 - [yldio/joyent-react-scripts](https://github.com/yldio/joyent-react-scripts)
 - [yldio/babel-preset-joyent-portal](https://github.com/yldio/babel-preset-joyent-portal)
 - [yldio/rnd-id](https://github.com/yldio/rnd-id)
 - [yldio/pseudo-yaml-ast](https://github.com/yldio/pseudo-yaml-ast)
 - [yldio/pseudo-json-ast](https://github.com/yldio/pseudo-json-ast)
 - [yldio/remcalc](https://github.com/yldio/remcalc)
 - [yldio/eslint-config-joyent-portal](https://github.com/yldio/eslint-config-joyent-portal)
 - [yldio/docker-compose-api](https://github.com/yldio/docker-compose-api)
