### ISSUE TITLE
Fix inconsistencies in technical Prototype

### ISSUE THREAD

**Issue by SaraVieira** [yldio/joyent-portal#682]
- [x] Group on selecting one appears switched
- [x] Sliders need to be reset
- [x] Clarifying design on buttons
- [x] Same horizontal and vertical margin
- [x] Number of sliders appear outside of the grid
- [ ] Sliders should only step to numbers that exist

**Comment by AlexJupiter** [comment]
- [ ] sliders sometimes can go over each other 
![image](https://user-images.githubusercontent.com/7900773/30539265-81d9eaf2-9c69-11e7-80af-35bb0bafa073.png)
- [ ]  blue highlight when a package is selected
