### ISSUE TITLE
Open Source UX / UI / Design

### ISSUE THREAD

**Issue by alex-windett** [yldio/joyent-portal#7]
Ideas and thoughts on how we should open source the design process.
## 

[http://ux.edx.org/](http://ux.edx.org/) - Another nice and simple site that is downloadable and editable. Breaks down a component into tabs (Example, Code, Styling)

[Salesforce](https://www.lightningdesignsystem.com/) have done a nice job and think it would be good structure to follow.

[Google's Material](https://material.google.com/) design have written up their thoughts and process of their design process.

I know Anthony mentioned this one and I think it is a good one.
[Patternfly](http://www.patternfly.org/pattern-library/#_) This one has an interesting and logic (to me at least) structure of items/objects/pages and their Overview, Design and Code.

Notes on the design system based off of [Salesforce Design System Talk](https://vimeo.com/181329002) - https://docs.google.com/document/d/1twTCsdz1lWMLXyx2axAbv9QLqegYYWVT1gfaMHIP9mo/edit?usp=sharing

**Comment by ajones5876** [comment]
Transferring this discussion to the new issue: https://github.com/yldio/joyent-portal/issues/225
