### ISSUE TITLE
Create Visual Regression tests for Styleguide Components

### ISSUE THREAD

**Issue by SaraVieira** [yldio/joyent-portal#703]
Options for this are:

- [ ] [WebdriverIO](http://webdriver.io/)
- [ ] [Navalia](https://github.com/joelgriffith/navalia) + [Jest Image Spanshot](https://www.npmjs.com/package/jest-image-snapshot)

Use Styleguidist node API: https://react-styleguidist.js.org/docs/api

**Comment by ramitos** [comment]
redundant with https://github.com/yldio/joyent-portal/issues/676
