### ISSUE TITLE
Choose code theme for styleguide

### ISSUE THREAD

**Issue by SaraVieira** [yldio/joyent-portal#712]
https://react-styleguidist.js.org/docs/configuration.html#highlighttheme

Themes: http://codemirror.net/demo/theme.html

**Comment by yaili** [comment]
First question is: light or dark?

My favourite is **base16-light** but I would like to tweak some things like spacing, borders, etc. Is that possible? **railscasts** is not bad either.

@antonasdeduchovas @AlexJupiter thoughts?

**Comment by SaraVieira** [comment]
> First question is: light or dark?
I prefer dark themes but I can go with either :)

> My favourite is base16-light
Good, thats the default one.

>  but I would like to tweak some things like spacing, borders, etc. Is that possible
Yes , sure , just tell me changes you want

**Comment by antonasdeduchovas** [comment]
@yaili as long as we have a lighter background, sure

**Comment by SaraVieira** [comment]
@yaili Can you let me know the changes you want in the code editor ?

**Comment by yaili** [comment]
- border #d8d8d8
- background #fafafa
- spacing (eg padding) to use multiples of 3px
- default text colour #494949
- line numbers text colour #636363

And then let's see if we need anything else. Thank you :)
