### ISSUE TITLE
Choose code font for the styleguide

### ISSUE THREAD

**Issue by SaraVieira** [yldio/joyent-portal#713]
At the momemnt the font we are using for code is Consolas and that does not look that good so any ideas would be awesome

http://hivelogic.com/articles/top-10-programming-fonts/
https://www.typewolf.com/top-10-monospaced-fonts

**Comment by yaili** [comment]
I think [Inconsolata](https://fonts.google.com/specimen/Inconsolata) would work well. 

@antonasdeduchovas any thoughts?

**Comment by antonasdeduchovas** [comment]
@yaili @SaraVieira 

I am just slightly concerned with their lower case. Look at that "t" - curvature of the stem is a bit too whimsical and irregular - sticks out like a sore thumb.

<img width="213" alt="screen shot 2017-10-04 at 16 20 25" src="https://user-images.githubusercontent.com/22451624/31183974-1808c2ec-a920-11e7-92f1-a7abe4de20dd.png">

and the apex of the upper case "A" is not trimmed - I feel cautious using untrimmed upper case letters in large bodies of text.

<img width="53" alt="screen shot 2017-10-04 at 16 23 38" src="https://user-images.githubusercontent.com/22451624/31184141-7ee048fa-a920-11e7-9d4d-f6cb89934ec0.png">

I might be a bit of a bore, but I'd suggest Roboto Mono (https://fonts.google.com/specimen/Roboto+Mono) - it has a lesser contrast, apex of A is properly trimmed, stems are strictly vertical - it's a well-rounded monospace typeface that retains a bit of that 'CLI' feel. And it has a larger variety of weights to choose from.

**Comment by yaili** [comment]
Oh yeah that "t" is a bit odd. I'm happy with Roboto Mono.

**Comment by antonasdeduchovas** [comment]
@yaili cool:)

**Comment by SaraVieira** [comment]
On it!
