### ISSUE TITLE
List DNS addresses (and show CNS names)

### ISSUE THREAD

**Issue by ramitos** [yldio/joyent-portal#725]
On each instance, have a DNS/CNS section where it should display the list of DNS addresses and CNS names assigned.

![image](https://user-images.githubusercontent.com/501018/31334771-97aedd90-ace7-11e7-8ed5-33db8e73ae8a.png)

**Comment by ramitos** [comment]
API to get CNS names? Do we have that? Can we rely on tags? Can we infer that from the DNS addresses?

**Comment by ramitos** [comment]
- [ ] add CNS/DNS section (inthe state obj)
 - [ ] list dns addresses (ideally in a ui like when we're listing firewall-rules/snapshots/instances, etc)
 - [] potentially list the CNS names

**Comment by AlexJupiter** [comment]
@ramitos are those questions above, things we should ask Casey tomorrow?
