### ISSUE TITLE
OOUX map

### ISSUE THREAD

**Issue by antonasdeduchovas** [yldio/joyent-portal#73]
**Initial task:**
Understand container-related content and actions. (Container setup, Scaling, Networking, Logs, Metrics, Metadata etc) -translate them into objects and CTAs.

.........

**Here's the first version of the Objects Map with CTAs**

https://drive.google.com/file/d/0B1oWObk56wa5T1BlTVl6a0JSQkU/view?usp=sharing

**Comment by antonasdeduchovas** [comment]
Updated object map:
https://drive.google.com/file/d/0B1oWObk56wa5ejl1ZEx2d1BNTnM/view?usp=sharing

**Comment by ajones5876** [comment]
Documented here:
