### ISSUE TITLE
Improve on Radio validation in UI Toolkit in figma 

### ISSUE THREAD

**Issue by SaraVieira** [yldio/joyent-portal#730]
In ui toolkit displayed in figma we have a single radio button with validation when in fact radio buttons need to be validated combined

**Comment by yaili** [comment]
I have changed it to have validation at the bottom of the list. I still need to look into the whole form validation. Shall I close this one, or do you need to track dev work?

**Comment by SaraVieira** [comment]
I can close this and create one to track development, thank you :)
