### ISSUE TITLE
update dependencies from other related repos

### ISSUE THREAD

**Issue by ramitos** [yldio/joyent-portal#741]
- [normalized-styled-components](https://github.com/yldio/normalized-styled-components)
- [styled-is](https://github.com/yldio/styled-is)
- [pseudo-yaml-ast](https://github.com/yldio/pseudo-yaml-ast)
- [pseudo-json-ast](https://github.com/yldio/pseudo-json-ast)
- [joyent-manifest-editor](https://github.com/yldio/joyent-manifest-editor)
- [unitcalc](https://github.com/yldio/unitcalc)
- [remcalc](https://github.com/yldio/remcalc)
- [rnd-id](https://github.com/yldio/rnd-id)
- [stylelint-config-joyent-portal](https://github.com/yldio/stylelint-config-joyent-portal)
- [joyent-react-scripts](https://github.com/yldio/joyent-react-scripts)
- [babel-preset-joyent-portal](https://github.com/yldio/babel-preset-joyent-portal)
- [eslint-config-joyent-portal](https://github.com/yldio/eslint-config-joyent-portal)

**Comment by ramitos** [comment]
https://github.com/yldio/eslint-config-joyent-portal/commit/3935e6854363042020b3114153005e760a049c82

**Comment by SaraVieira** [comment]
@ramitos why no install greenkeeper?

**Comment by ramitos** [comment]
@SaraVieira good idea! I didn't enable it in this repo because it doesn't support monorepos, but I could enable it in the other repos. 

For this time, I'm not only updating deps, I'm also reviewing some details.

**Comment by ramitos** [comment]
[yldio/babel-preset-joyent-portal@be5d54d](https://github.com/yldio/babel-preset-joyent-portal/commit/be5d54d264388fb97ace941f807e5603c7d8a0f3)

**Comment by SaraVieira** [comment]
I'll then add it to the repos if that is okay :)
Also add bundlesize :)

**Comment by ramitos** [comment]
@SaraVieira 👍

**Comment by ramitos** [comment]
[yldio/normalized-styled-components@ff9640c](https://github.com/yldio/normalized-styled-components/commit/ff9640c08992a0ebe0f7ac4ad77e49fc875c94ab)
[yldio/normalized-styled-components@3143038](https://github.com/yldio/normalized-styled-components/commit/3143038435c7de46495bbb4829c706900c5f70df)
[yldio/normalized-styled-components@f87b814](https://github.com/yldio/normalized-styled-components/commit/f87b81437096270c003ae7e719e7d4e448bcdfd7)
[yldio/styled-is@90c1ab4](https://github.com/yldio/styled-is/commit/90c1ab427d0f4103f881bbf7da77dbbd5fe042cd)
[yldio/styled-is@43295df](https://github.com/yldio/styled-is/commit/43295dfd3d08e4e9ee80c78dc597ab45bc5b58f3)
[yldio/pseudo-yaml-ast@6c42c49](https://github.com/yldio/pseudo-yaml-ast/commit/6c42c498e0409033d6e567afcf603d80ada3f61c)
[yldio/pseudo-yaml-ast@fdb4e9d](https://github.com/yldio/pseudo-yaml-ast/commit/fdb4e9dcd698fe6d898688e17758411ad16c4ad3)
[yldio/pseudo-yaml-ast@bf2eea7](https://github.com/yldio/pseudo-yaml-ast/commit/bf2eea79e2d0e64b3a9dbfe091109503c36bb223)
[yldio/pseudo-yaml-ast@de4b8d4](https://github.com/yldio/pseudo-yaml-ast/commit/de4b8d4978e7f55803d83080a448b5ff7b3cb2b0)
[yldio/pseudo-json-ast@35ee757](https://github.com/yldio/pseudo-json-ast/commit/35ee75754dce7782cefe5588af518d258a62bd87)
[yldio/joyent-manifest-editor@1be98da](https://github.com/yldio/joyent-manifest-editor/commit/1be98daab0ecbedb8fa76ccea92d3c29229d08b9)
[yldio/unitcalc@dcfc861](https://github.com/yldio/unitcalc/commit/dcfc861e0ef35e46cde7a178ae2ee0d6841b4a19)
[yldio/unitcalc@402aea3](https://github.com/yldio/unitcalc/commit/402aea382094ff00388fff4aaf1ec8e8b75c2108)
[yldio/remcalc@6d685d1](https://github.com/yldio/remcalc/commit/6d685d1d2dde9c5c75874213629888c0405208ea)
[yldio/rnd-id@b1f3c50](https://github.com/yldio/rnd-id/commit/b1f3c500ab2c312dec0c6aac21c0fcbb7ae48641)
[yldio/rnd-id@acf745e](https://github.com/yldio/rnd-id/commit/acf745e3867cdcf06924af7b87ac348a802d2046)
[yldio/stylelint-config-joyent-portal@5ace9cb](https://github.com/yldio/stylelint-config-joyent-portal/commit/5ace9cbf7334ea81bdedbda8241360370c5102d0)
[yldio/stylelint-config-joyent-portal@cf0a510](https://github.com/yldio/stylelint-config-joyent-portal/commit/cf0a5107f17a69497019a0d93607fca41ff68424)
[yldio/joyent-react-scripts@9e9802f](https://github.com/yldio/joyent-react-scripts/commit/9e9802f55ab84d573d8297c62c9950fe0192b121)
[yldio/joyent-react-scripts@e6c2a0c](https://github.com/yldio/joyent-react-scripts/commit/e6c2a0cefd13b36c4adb959786f30d38bd909299)
[yldio/joyent-react-scripts@4899f7e](https://github.com/yldio/joyent-react-scripts/commit/4899f7e4e5c8fb608e4f2172141bb8516a832fa1)
[yldio/babel-preset-joyent-portal@be5d54d](https://github.com/yldio/babel-preset-joyent-portal/commit/be5d54d264388fb97ace941f807e5603c7d8a0f3)
[yldio/babel-preset-joyent-portal@075b9ab](https://github.com/yldio/babel-preset-joyent-portal/commit/075b9abba16574d689f5d573f3249c5d062e7f2a)
[yldio/eslint-config-joyent-portal@eb888eb](https://github.com/yldio/eslint-config-joyent-portal/commit/eb888ebee75226e18613ca4bb79273d24d45a950)
[yldio/eslint-config-joyent-portal@3935e68](https://github.com/yldio/eslint-config-joyent-portal/commit/3935e6854363042020b3114153005e760a049c82)
