### ISSUE TITLE
wrong styles in button loading states

### ISSUE THREAD

**Issue by ramitos** [yldio/joyent-portal#749]
- `loading` and `disabled` (secondary and primary buttons)

![image](https://user-images.githubusercontent.com/501018/31502486-1d0db91e-af65-11e7-9d11-5617000bc133.png)

 - [ ] Loading copy should be on the right, not in a line break

 - `loading` only (secondary and primary buttons)

![image](https://user-images.githubusercontent.com/501018/31502581-6d927fbe-af65-11e7-801f-d72779a21c73.png)

 - [ ] Loading copy should be on the right, not in a line break
 - [ ] Animation color (in the primary button) should be the same as the copy

**Comment by ramitos** [comment]
cc @SaraVieira @yaili

**Comment by yaili** [comment]
@antonasdeduchovas thoughts? 🤔

**Comment by antonasdeduchovas** [comment]
@yaili I'd suggest sticking to just one style of a loading button, regardless of it's default properties (being primary, secondary or disabled). I assume that while loading is in progress, the component cannot be activated, so maybe using a style for disabled button + loading animation and label in one line would make sense

**Comment by yaili** [comment]
@antonasdeduchovas how about just the icon? unless the loading can stay on for a long time, which prob shouldn't happen anyway…

**Comment by antonasdeduchovas** [comment]
@yaili I agree

**Comment by SaraVieira** [comment]
On it !

Just the icon and always have the disabled state.

Thanks guys :)
