### ISSUE TITLE
Explore how different environments fit into the application structure (Dev, Staging, Prod etc)

### ISSUE THREAD

**Issue by antonasdeduchovas** [yldio/joyent-portal#75]
We had an initial workshop, here's a brief report:
https://drive.google.com/open?id=0B1oWObk56wa5U3pTZEtZc2E4blU

We need to gather a bit more feedback from the users, but certain UI components are already being introduced to the wireframes

**Comment by ajones5876** [comment]
Documented in wiki: https://github.com/yldio/joyent-portal/wiki/10.11.16:-Explore-how-different-environments-fit-into-the-application-structure-(Dev,-Staging,-Prod-etc)
