### ISSUE TITLE
Instance tags empty state

### ISSUE THREAD

**Issue by ramitos** [yldio/joyent-portal#760]

**Comment by ramitos** [comment]
It should probably suggest to create a new instance

**Comment by hollowtf** [comment]
I have updated the tags section of instance management to include alterations for the Edit button (as discussed with Sergio) and have included an empty state when no tags exist.

https://www.figma.com/file/cK42HPiq1KHmjtCu1yy766Sd/IM-Tags?node-id=89%3A115

**Comment by yaili** [comment]
The "Add tag" and "Edit tags" buttons should be capitalised—Add Tags, Edit Tags—for consistency. Otherwise looking great.

**Comment by hollowtf** [comment]
👍 Updated 👍
