### ISSUE TITLE
Instance firewall empty state

### ISSUE THREAD

**Issue by ramitos** [yldio/joyent-portal#763]

**Comment by ramitos** [comment]
if enabled, it should probably suggest to create a new firewall rule

**Comment by hollowtf** [comment]
Empty states for firewalls have been implemented. As there is currently no way to add a firewall from this console, I have omitted the 'No firewall' empty state.

No filter results:
https://www.figma.com/file/NGsNEXdI0ywbGaGOe07SPIUd/IM-Firewall?node-id=7%3A341
