### ISSUE TITLE
Instance snapshots empty state

### ISSUE THREAD

**Issue by ramitos** [yldio/joyent-portal#764]

**Comment by ramitos** [comment]
it should probably suggest to create a new snapshot

**Comment by hollowtf** [comment]
All done

No snapshots:
https://www.figma.com/file/Ox99vAFeABmr1RvQsQ8sDDJK/IM-Snapshot?node-id=82%3A732

No filter results:
https://www.figma.com/file/Ox99vAFeABmr1RvQsQ8sDDJK/IM-Snapshot?node-id=82%3A982
