### ISSUE TITLE
Create Topology Package

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#769]

**Comment by ramitos** [comment]
Considering that the implementation is tightly coupled with our use cases (including healthy/unhealthy, consul, etc), `react-topology` might be a too generic name, no?

**Comment by SaraVieira** [comment]
This is not tied to consul anymore , most of it is now generic you can pass anything else with the map function 

But it may be too generic and if you have a better name that would be aawesome !
