### ISSUE TITLE
better tooltip implementation

### ISSUE THREAD

**Issue by ramitos** [yldio/joyent-portal#771]
- [ ] composable - should work well for tooltips and menus
 - [ ] versatile - should work with mouseover and click/click
 - [ ] good ux - https://www.youtube.com/watch?v=90NsjKvz9Ns
 - [ ] dynamic - should move around as it needs more space
 - [ ] react api

**Comment by ramitos** [comment]
ideas: 

React:
 - https://github.com/react-component/tooltip (seems to be match all our needs)
 - https://github.com/darsain/tooltip
 - https://github.com/souporserious/react-popper

Js: 
 - https://github.com/FezVrasta/popper.js
 - https://github.com/jhartman86/internetips

jQuery based:
 - https://osvaldas.info/elegant-css-and-jquery-tooltip-responsive-mobile-friendly
 - http://www.tipue.com/tipr/
 - https://github.com/iamceege/tooltipster
 - https://github.com/jaz303/tipsy

**Comment by SaraVieira** [comment]
This ticket also incorporates creating examples for usage in quick actions
