### ISSUE TITLE
let's talk icons

### ISSUE THREAD

**Issue by ramitos** [yldio/joyent-portal#772]
I think we should adopt an icon library, but we need to choose which and how.

## Requirements: 
 - SVG only
 - open source
 - has all icons that we need

#### stackable
![image](https://user-images.githubusercontent.com/501018/31661757-c4c5d2f0-b333-11e7-83bc-63f95edbfec6.png)
![image](https://user-images.githubusercontent.com/501018/31661851-1c2d861e-b334-11e7-99ce-6208407b4f32.png)
![image](https://user-images.githubusercontent.com/501018/31661865-2a68344a-b334-11e7-9590-66207be7d883.png)

#### overlays
![image](https://user-images.githubusercontent.com/501018/31661886-389cc7d8-b334-11e7-9d48-587321c5b21e.png)

#### size
![image](https://user-images.githubusercontent.com/501018/31661653-63d485c2-b333-11e7-84b1-fc93856795e0.png)

#### color
![image](https://user-images.githubusercontent.com/501018/31661675-76dbdcce-b333-11e7-87ce-8ff5a20f5a1d.png)

#### fixed width
![image](https://user-images.githubusercontent.com/501018/31661714-9b46a288-b333-11e7-8ba3-022cf47f4300.png)

#### rotatable
![image](https://user-images.githubusercontent.com/501018/31661746-b913cb9c-b333-11e7-8d90-6f1b74ff4a43.png)

#### positionable 
![image](https://user-images.githubusercontent.com/501018/31661804-ebb4ce02-b333-11e7-9a21-e68fd782c9ad.png)

## Options
 - https://feathericons.com/
 - https://fontawesome.com/
 - https://material.io/icons/
 - https://useiconic.com/open
 - http://s-ings.com/typicons/
 - https://octicons.github.com/
 - http://ionicons.com/

**Comment by SaraVieira** [comment]
https://github.com/gorangajic/react-icons

**Comment by ramitos** [comment]
@SaraVieira yes, I'm aware, but since we should integrate the library in the ui-toolkit, I think we should build our own "react-icons" implementation ;)

**Comment by SaraVieira** [comment]
OHHHHHH ! Got it !

This should be a call then :)

**Comment by ramitos** [comment]
@SaraVieira yes ;)

**Comment by yaili** [comment]
Summary of discussion: we'll design icons as needed for now, but will define guidelines for icon design.
