### ISSUE TITLE
Create NextJS Boilerplate

### ISSUE THREAD

**Issue by SaraVieira** [yldio/joyent-portal#773]
Create Folder for prototypes and get it up and running with the ui toolkit and NextJS

https://zeit.co/blog/next4

**Comment by ramitos** [comment]
started an implementation in https://github.com/yldio/joyent-portal/commit/4f54a2bdc13ac1b2c4548d964f2b08e6af2522e6 with no success because I was unable to get Fonts and CSS from dependencies to work. 

@SaraVieira can you give it a try?
