### ISSUE TITLE
review IconButton

### ISSUE THREAD

**Issue by ramitos** [yldio/joyent-portal#781]
potentially move into Button, or remove if there is a better solution

**Comment by ramitos** [comment]
@yaili we might need a button with icon design

**Comment by yaili** [comment]
What we decided in the inventory workshop was that we should have icons that can be composed with buttons. I have spoken with @antonasdeduchovas about the design guidelines for having buttons with icons, I can add it to Figma.

**Comment by yaili** [comment]
@ramitos Shall I remove discussion and engineering and design is done?

**Comment by ramitos** [comment]
@yaili yes, that's what I remember too. What that means is that we shouldn't have an `<IconButton />`. We should have a `<Button><Icon /></Button>`. Which is why this `<IconButton />` should be removed

**Comment by ramitos** [comment]
@yaili just removed `discussion` 😉
