### ISSUE TITLE
Layout (navigation,taxonomy)

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#784]

**Comment by AlexJupiter** [comment]
Prioritisation of Core Content and CTAs conducted here: https://www.figma.com/file/NUyFV996nEV5XoMTZuD4p2jO/Instance-Core-Content-and-Metadata-Prioritisation

**Comment by AlexJupiter** [comment]
Initial designs:
- [List view](https://www.figma.com/file/H1YwX8ezmycCdbWzG25Ya2sa/Instance-Management%3A-iterations?node-id=1%3A2)
- [List view with CTAs](https://www.figma.com/file/H1YwX8ezmycCdbWzG25Ya2sa/Instance-Management%3A-iterations?node-id=13%3A984)

Clicking on the instance name in the above design would then take you to the "Overview" presenting the rest of the information on that instance:

- [Overview](https://www.figma.com/file/H1YwX8ezmycCdbWzG25Ya2sa/Instance-Management%3A-iterations?node-id=13%3A55)
- [Overview with feed iteration 1](https://www.figma.com/file/H1YwX8ezmycCdbWzG25Ya2sa/Instance-Management%3A-iterations?node-id=13%3A241)
- [Overview with feed iteration 2](https://www.figma.com/file/H1YwX8ezmycCdbWzG25Ya2sa/Instance-Management%3A-iterations?node-id=13%3A479)

I also did some designs with an 'expanded card' for the instance list. However, it proved difficult to find space for an accordion, CTAs and a checkbox for bulk actions. Plus, I wasn't convinced with the expanded card anyway. Regardless, the start of the flow can be seen and then scroll down for the next steps:
- [Instance list with expanded card](https://www.figma.com/file/H1YwX8ezmycCdbWzG25Ya2sa/Instance-Management%3A-iterations?node-id=7%3A5)

**Comment by AlexJupiter** [comment]
I did an iteration on the sorting for the instance list. This concept could also be relevant for anywhere we have a table, especially related to https://github.com/yldio/joyent-portal/issues/795.

https://www.figma.com/file/H1YwX8ezmycCdbWzG25Ya2sa/Instance-Management%3A-iterations?node-id=29%3A0

**Comment by AlexJupiter** [comment]
Some new iterations following the [feedback](https://www.figma.com/file/H1YwX8ezmycCdbWzG25Ya2sa/Instance-Management%3A-iterations?node-id=13%3A55) from this morning:
- [New design for the instance list](https://www.figma.com/file/H1YwX8ezmycCdbWzG25Ya2sa/Instance-Management%3A-iterations?node-id=41%3A0). There should now be a clearer association between selecting an instance and putting an action on it. I also improved the general spacing around the breadcrumb and thought about the hierarchy of the buttons. We now have a prominent CTA that is the main action a user would commit on this page, and then secondary CTAs below. 
-[ I did a small iteration on this.](https://www.figma.com/file/H1YwX8ezmycCdbWzG25Ya2sa/Instance-Management%3A-iterations?node-id=42%3A0), that simply removes the <hr/>.
- [An improved instance summary is here](https://www.figma.com/file/H1YwX8ezmycCdbWzG25Ya2sa/Instance-Management%3A-iterations?node-id=42%3A485). Implementing some of the general feedback from this morning as well as the previously mentioned improvements in the hierarchy and spacings.

**Comment by AlexJupiter** [comment]
Updated designs: https://www.figma.com/file/R54EYOFwKGRaAibgCTpHmQe9/Instance-Management

Came up with a new button for "actions" and a modal for changing columns.

Expecting reactions ;)

**Comment by AlexJupiter** [comment]
@yaili and I conducted some sketches for the instance summary:
![image](https://user-images.githubusercontent.com/7900773/32042255-d376587c-ba2e-11e7-9076-1e384bbec161.png)
![image](https://user-images.githubusercontent.com/7900773/32042264-da344b92-ba2e-11e7-9823-1680276bf956.png)
![image](https://user-images.githubusercontent.com/7900773/32042271-dfb39802-ba2e-11e7-9789-6a1e2e34d18c.png)

**Comment by AlexJupiter** [comment]
I've taken the above sketches and implemented a wireframe [here](https://www.figma.com/file/H1YwX8ezmycCdbWzG25Ya2sa/Instance-Management%3A-iterations?node-id=138%3A448). Feedback please! 

@yaili this definitely needs some visual design work. As mentioned in previous iterations, it's looking very 'bland'.

We can improve with some of the icons I used for my designs for the CTAs (https://github.com/yldio/joyent-portal/issues/785) and we also need to add icons for things that should have a quick access for copying to clipboard.

**Comment by AlexJupiter** [comment]
Updated the wireframes for instance list: https://www.figma.com/file/R54EYOFwKGRaAibgCTpHmQe9/Instance-Management

Specifically regarding Casey's feedback, that:
- we could remove export to CSV
- quick actions should complement bulk actions

**Comment by AlexJupiter** [comment]
@yaili we need work on the iconography for the bulk actions footer CTAs

**Comment by AlexJupiter** [comment]
Initial work on the instance summary has been conducted here: https://www.figma.com/file/H1YwX8ezmycCdbWzG25Ya2sa/Instance-Management-iterations?node-id=138%3A448

**Comment by yaili** [comment]
@AlexJupiter we should separate instance summary to another issue

**Comment by AlexJupiter** [comment]
Opened new issue here: https://app.zenhub.com/workspace/o/yldio/joyent-portal/issues/825

**Comment by AlexJupiter** [comment]
We still need to add icons here.

This will be transferred to an engineering task, with an icon issue inside.
