### ISSUE TITLE
Update tags and metadata 

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#789]
Use designs for affinity as inspiration (making them into 'objects')

**Comment by yaili** [comment]
Initial look at this:
- **[Tags 1A](https://www.figma.com/file/NVIbR3uRLK4GE2hwjS9P2KAx/Create-instance%3A-mega-accordion-iterations?node-id=10%3A0)**: copied straight from Affinity
- **[Tags 1B](https://www.figma.com/file/NVIbR3uRLK4GE2hwjS9P2KAx/Create-instance%3A-mega-accordion-iterations?node-id=11%3A54)**: same but closed
- **[Metadata 1A](https://www.figma.com/file/NVIbR3uRLK4GE2hwjS9P2KAx/Create-instance%3A-mega-accordion-iterations?node-id=11%3A199)**: copied from Affinity
- **[Metadata 1B](https://www.figma.com/file/NVIbR3uRLK4GE2hwjS9P2KAx/Create-instance%3A-mega-accordion-iterations?node-id=11%3A345)**: same but closed

I can continue to improve this, but wanted to keep the pattern as similar as Affinity/Alerts as possible. Thoughts?

**Comment by AlexJupiter** [comment]
**Tags** 
- Look good
- Perhaps there needs to be an improved visual clarity between the key and value? Perhaps bolding the colon? Like key **:** value. I imagine if there were a great deal of tags then it would be difficult to read otherwise.

**Metadata**
- the value could be multiple lines of code. How is this going to be represented in the collapsed view?

**Comment by AlexJupiter** [comment]
Okay, my bolding the colon really doesn't work on GitHub! But I hope my point still makes sense!

**Comment by yaili** [comment]
@AlexJupiter it could be with an ellipsis

**Comment by AlexJupiter** [comment]
@yaili an ellipsis separating the key and value? I'm not sure that's the correct convention and could cause confusion. Right @ramitos?

**Comment by yaili** [comment]
@AlexJupiter no, an ellipsis at the end of the value if it's too long to fit

**Comment by yaili** [comment]
@AlexJupiter shall we close this?
