### ISSUE TITLE
Reorder

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#790]

**Comment by yaili** [comment]
@AlexJupiter did you have an updated order? could you paste it here?

**Comment by yaili** [comment]
@AlexJupiter did you have an updated order? could you paste it here?

**Comment by AlexJupiter** [comment]
New order is proposed here that puts tags right after package selection: https://www.figma.com/file/NVIbR3uRLK4GE2hwjS9P2KAx/Create-instance-mega-accordion-iterations?node-id=209%3A0

The reason for this is so every section that has a relationship with tags can be easily referenced, in that future section.

**Comment by yaili** [comment]
Can we close? 🤔

**Comment by AlexJupiter** [comment]
Just want to double check this with @ramitos first

**Comment by AlexJupiter** [comment]
@ramitos need your approval here :)

**Comment by ramitos** [comment]
@AlexJupiter @yaili looks good to me 👍
