### ISSUE TITLE
Improve the design of the instance creation summary

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#792]

**Comment by yaili** [comment]
I've made only small changes here, following a chat with @antonasdeduchovas yesterday:

- **[Summary 1](https://www.figma.com/file/NVIbR3uRLK4GE2hwjS9P2KAx/Create-instance%3A-mega-accordion-iterations?node-id=1%3A10)**: the summary boxes are all the same size, unless the content is too long
- **[Summary 2](https://www.figma.com/file/NVIbR3uRLK4GE2hwjS9P2KAx/Create-instance%3A-mega-accordion-iterations?node-id=1%3A142)**: the summary boxes are all same size, with content adapted to fit
- **[Summary 3](https://www.figma.com/file/NVIbR3uRLK4GE2hwjS9P2KAx/Create-instance%3A-mega-accordion-iterations?node-id=3%3A67)**: included placeholder icons in all sections, adding some playfulness to the screen
- **[Summary 4](https://www.figma.com/file/NVIbR3uRLK4GE2hwjS9P2KAx/Create-instance%3A-mega-accordion-iterations?node-id=17%3A0)**: summary boxes in middle column, saving some vertical space

Thoughts welcome. Do you feel any of these is an improvement?

**Comment by AlexJupiter** [comment]
Summary 4 is definitely my favourite:
- it makes the page even shorter (we've come such a long way!!!)
- it reduces the unnecessary information that I think clutters Summary 1
- I would question the use of icons though. I don't actually think they are adding anything, and I realise they are placeholders. Even if we dedicated time to these icons (which I don't think we really have unless @antonasdeduchovas is going to do this in his hectic schedule) any icon trying to add clarity to such technical terms is bound to be ambiguous (thinking back to CoPilot testing we've had trouble finding the right icons for 'simple' things like re-ordering and instance - let alone something like Affinity).

**Comment by antonasdeduchovas** [comment]
@AlexJupiter Iconography would support text labels and bring more visual delight. We've already agreed with @yaili that if needed, I'll help with the icons during my next "Joyent Friday"

**Comment by AlexJupiter** [comment]
@antonasdeduchovas I agree that they would add more visual delight. But only if we get them right and I just think it's a great deal of work (and there are more important things at the moment that we could use your expertise on). In our latest CoPilot testing sessions users were confused by our instance icon - which to me proves that these icons will need to go through many iterations and be user tested.

Perhaps illustrations would be nice (so something larger that supports the whole section - not just the title). But again, i'd question the necessity at this stage.

**Comment by antonasdeduchovas** [comment]
@AlexJupiter as long as you don't forget about it - sure :D

**Comment by yaili** [comment]
For completeness:
- **[Summary 5](https://www.figma.com/file/NVIbR3uRLK4GE2hwjS9P2KAx/Create-instance%3A-mega-accordion-iterations?node-id=36%3A377)**: icons, but smaller
- **[Summary 6](https://www.figma.com/file/NVIbR3uRLK4GE2hwjS9P2KAx/Create-instance%3A-mega-accordion-iterations?node-id=36%3A246)**: no icons, in columns (looks a bit plain…)

**Comment by yaili** [comment]
Feedback to explore:
- [ ] Incorporate more icons within the content of the summary
- [ ] Tags more visual
- [ ] Remember to reorder

**Comment by AlexJupiter** [comment]
@yaili could we change this to "Creation Summary"? I'm getting confused what we mean by when we say "Summary" (as per our conversation last night). The "Summary" in instance management can then be called "Instance Summary". What do you think?

**Comment by yaili** [comment]
@AlexJupiter did we talk about this yesteday? Any thoughts on whether this is done for now?

**Comment by yaili** [comment]
We agreed to close this for now.
