### ISSUE TITLE
Improve the relationship between firewall and tags

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#793]

**Comment by AlexJupiter** [comment]
Created a design that splits up general firewall rules and firewall rules specifically related to tags on the instance: https://www.figma.com/file/NVIbR3uRLK4GE2hwjS9P2KAx/Create-instance-mega-accordion-iterations?node-id=209%3A111

If the user wants to change the "firewall tag rules" they can always go back and add and delete tags. Because the focus of instance creation, is creating instances, we are not providing any other functionality here in terms of setting up firewall rules, we are purely highlighting the relationship between tags and firewall rules here that a user can always edit later in the firewall rule section.

**Comment by AlexJupiter** [comment]
@ramitos need your approval here as well :)

**Comment by ramitos** [comment]
@AlexJupiter  added a comment ;)
