### ISSUE TITLE
Add educational copy to each section

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#794]

**Comment by AlexJupiter** [comment]
Creating the educational copy in this doc: https://docs.google.com/document/d/1BS5EEEzmkgURSMrJzCnZpSxwW5wNj4b2P6zbmrTIMgQ/edit

**Comment by AlexJupiter** [comment]
First draft of the educational copy is here: 
https://docs.google.com/document/d/1BS5EEEzmkgURSMrJzCnZpSxwW5wNj4b2P6zbmrTIMgQ/edit#

Feedback needed inside the doc or in here.

**Comment by AlexJupiter** [comment]
the descriptions for network(s) are holding this back, I need to clarify this with Casey tomorrow. Depending on the answer, we can create a v1.

**Comment by yaili** [comment]
@AlexJupiter did you clarify with Casey?

**Comment by AlexJupiter** [comment]
@ramitos could we please have your eye here please? Especially concerning the description for networks.

**Comment by ramitos** [comment]
added a bunch of notes

**Comment by AlexJupiter** [comment]
I'd like to close this as I feel like we now have a good first draft of this. Any thoughts?
