### ISSUE TITLE
Multi-region Dashboard.

### ISSUE THREAD

**Issue by tomgco** [yldio/joyent-portal#8]
Joyent / Triton Cloud and the on-premise version of this can run in a multitude of data-centres.

```
eu-ams-1          -     https://eu-ams-1.api.joyent.com
us-east-1         -     https://us-east-1.api.joyent.com
us-east-2         -     https://us-east-2.api.joyent.com
us-east-3         -     https://us-east-3.api.joyent.com
us-sw-1           -     https://us-sw-1.api.joyent.com
us-west-1         -     https://us-west-1.api.joyent.com
```

We need to think about how host the dashboard itself.
- Do we run an instance of the dashboard in each data centre?
  - If we do this how do we ensure that a client connects to the best endpoint for them?

**Comment by ramitos** [comment]
no longer relevant
