### ISSUE TITLE
DAY 2 Workshop/Discussion (Casey in London): Rollbacks and Version Control

### ISSUE THREAD

**Issue by alex-windett** [yldio/joyent-portal#80]
Rollback to previous version and viewing previous versions on current project / service

https://docs.google.com/a/make-us-proud.com/document/d/1-sVgHruGO8CBGVnCYZK0TTiI-Zu_otbMzebDPz-xDhY/edit?usp=sharing

**Comment by ramitos** [comment]
no longer relevant
