### ISSUE TITLE
Instance List

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#805]
A user must be able to view all instances they have deployed in a data center to allow them to judge the overall performance of their instance and make quick actions.

KPIs:
1. A user must be able to judge very high level information on their instance (such as name and status)
2. A user must be able to perform quick actions on instances (such as stop and restart), singularly, and in bulk
3. A user should be able to find a specific instance from a large number

**Comment by yaili** [comment]
Closing as it's duplicate of #783 - confidence label moved to original epic.
