### ISSUE TITLE
Snapshots

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#806]

**Comment by AlexJupiter** [comment]
- [Created the first iteration of this here](https://www.figma.com/file/H1YwX8ezmycCdbWzG25Ya2sa/Instance-Management%3A-iterations?node-id=42%3A149).
- Subsequent iterations are viewable [here](https://www.figma.com/file/H1YwX8ezmycCdbWzG25Ya2sa/Instance-Management%3A-iterations?node-id=41%3A148), and [here](https://www.figma.com/file/H1YwX8ezmycCdbWzG25Ya2sa/Instance-Management%3A-iterations?node-id=42%3A311) that are simply moving the hr around.

**Comment by AlexJupiter** [comment]
Feedback appreciated as always!

**Comment by AlexJupiter** [comment]
New iteration here: https://www.figma.com/file/R54EYOFwKGRaAibgCTpHmQe9/Instance-Management?node-id=63%3A392

Using new instance list layout.

Subsequent flows in snapshots are directly below the first frame in the Figma file. 

Need to answer questions on date formats (however we can tackle this in the next sprint) and also should updated and created have different status colours?

**Comment by AlexJupiter** [comment]
We need date in the title.

**Comment by yaili** [comment]
What happens when you click "Create snapshot"?

**Comment by AlexJupiter** [comment]
Not sure - this needs to be designed ASAP (I'll get onto it tomorrow)

**Comment by AlexJupiter** [comment]
![image](https://user-images.githubusercontent.com/7900773/32610796-b9679df0-c55b-11e7-9b79-8c84abe1111b.png)

**Comment by AlexJupiter** [comment]
@ramitos @SaraVieira @hollowtf any feedback on this for snapshots: https://www.figma.com/file/Ox99vAFeABmr1RvQsQ8sDDJK/Snapshots?node-id=6%3A6 ?

**Comment by AlexJupiter** [comment]
Marvel prototype made out of the above Figma file: https://marvelapp.com/116d7j46/screen/34626153

**Comment by yaili** [comment]
Cool. I've added some comments on Figma.

**Comment by AlexJupiter** [comment]
I think this can be closed. the remaining feedback can be split into a new issue related to bulk actions. Thoughts?

**Comment by yaili** [comment]
Sure, will you open a new issue?
