### ISSUE TITLE
rethink Card

### ISSUE THREAD

**Issue by ramitos** [yldio/joyent-portal#809]
- [ ] remove `flat`, `topMargin`, `bottomless`, and `gapless`. The need for those can be avoided with a table api
- [ ] `primary`, `secondary` and `tertiary`
- [ ] replace `selected` with `active`
- [ ] move paper-effect to it

```jsx
<Card>
  <CardHeader>
    <CardHeaderBox left /> {/* for checkboxes */ }
    <CardHeaderView /> {/* row, labels can be labels and be used as needed */ }
    <CardHeaderBox right /> {/* for quick-actions */ }
  </CardHeader>
  <CardOutlet /> {/* open box, use as needed */ }
</Card>
```

| Prop name    | Type   | Default |
|--------------|--------|---------|
| `children`   | `node` | `null`  |
| `collapsed`  | `bool` | `false` |
| `primary`    | `bool` | `true`  |
| `secondary`  | `bool` | `false` |
| `tertiary`   | `bool` | `false` |
| `disabled`   | `bool` | `false` |
| `stacked`    | `bool` | `false` |
| `active`     | `bool` | `false` |
| `shaddow`    | `bool` | `false` |
| `actionable` | `bool` | `false` |

**Comment by SaraVieira** [comment]
your tickets are just deep sometimes

**Comment by ramitos** [comment]
@SaraVieira 😂
