### ISSUE TITLE
Header Redesign

### ISSUE THREAD

**Issue by SaraVieira** [yldio/joyent-portal#820]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] design request

* **What is the current behavior?**
The header does not look like the the designs: 
https://www.figma.com/file/gqM6qlvj1BQUrzirXz3wss7n/Navbar?node-id=1%3A7

* **What is the expected behavior?**
The header should look like the designs

**Comment by ramitos** [comment]
tip: The `<Header />` implementation in my-joy-beta uses a `<ViewContainer />`. That `<ViewContainer />` can be `fluid` so that it doesn't limit the width.
