### ISSUE TITLE
Instance management home

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#825]
Initial work on the instance summary has been conducted here: https://www.figma.com/file/H1YwX8ezmycCdbWzG25Ya2sa/Instance-Management-iterations?node-id=138%3A448

**Comment by yaili** [comment]
@AlexJupiter shall I work on this today? ☺️

**Comment by yaili** [comment]
Here's a first draft of the [design](https://www.figma.com/file/V4GeNtzgy2DY1EJlDGnRiCJK/Instance-management%3A-iterations-3?node-id=1%3A16) for instance summary

Some notes:
- The 3 sections Login, IDs, Addresses probably still need some work as they all look the same
- How could Login be displayed in an interesting way?
- It makes sense to list all IDs together, I think from all 3 sections that look the same, this one is the one that makes more sense to look like this
- IP addresses has 2 addresses in the design. In this case, how could the copy to clipboard function work? Would it even be useful for this info?
- Is there a way to condense this layout further? Right now I've left it optimised for mobile, but we could think of something clever for wider screens
- I removed the toggles from previous versions, I'm not sure of their value at this stage
- Could icons help in the instance and package sections?

Any ideas on things to try next would be great!

cc @antonasdeduchovas @AlexJupiter @ramitos @SaraVieira

**Comment by yaili** [comment]
[Another version](https://www.figma.com/file/V4GeNtzgy2DY1EJlDGnRiCJK/Instance-management%3A-iterations-3?node-id=14%3A0) integrating some of the feedback.

**Comment by yaili** [comment]
Feedback from review:
- Consider what happens when you click Edit package
- Consider adding more info to this screen (e.g. firewall, tags, …)

**Comment by AlexJupiter** [comment]
Apologies if I wasn't clear with my feedback in this morning's meeting, however in summary, my feedback on where the designs are at the moment are as follows:
- I feel like the priorities we decided beforehand, [here](https://www.figma.com/file/NUyFV996nEV5XoMTZuD4p2jO/Instance-Core-Content-and-Metadata-Prioritisation), are a good starting point. (I am concerned we missed out tags and metadata in that workshop though)
- I looked at the Optimal Workshop card sort that Anthony mentioned, discussed this with Antonas, and the conclusion was that it wasn't that useful for us at the moment due to the amount of information sorted in this experiment and the small sample size. If people want to have a look at this I've just posted the login details in Slack #internal channel.
- I also feel like our previous iterations [here](https://www.figma.com/file/V4GeNtzgy2DY1EJlDGnRiCJK/Instance-management-iterations-3?node-id=1%3A16) are more in line with what I think would be more useful for the user. That said, @ramitos @SaraVieira could you both please confirm the usefulness of having all of this information copyable? If you could both have a careful look at the groupings as well that would be helpful. 
- I think the problem around resizing the package is still something that requires more work, our conversations with Antonas this morning where we highlighted that a singular package has a different user interaction than multiple tags (or meta data, or affinity rules etc) is something to consider. I would be tempted to suggest that having a CTA on a package that says "resize", which then takes the user to another page (not a tab) where the "Package Picker" would be displayed, would be an interesting solution to mockup.

**Comment by AlexJupiter** [comment]
I did an iteration where the instance summary is restricted to high level information of the instance, and then each tab is the same as for instance creation.

It's heavily inspired by one of Yaili's previous iterations and also Tom's new design patterns on the instance creation summary. [Go here](https://www.figma.com/file/V4GeNtzgy2DY1EJlDGnRiCJK/Instance-management-iterations-3?node-id=219%3A1500)

I also did an iteration around how a user would resize their package. Resizing package will open up a new page, signified in the breadcrumb, with the current package disabled in the table. [Go here](https://www.figma.com/file/V4GeNtzgy2DY1EJlDGnRiCJK/Instance-management-iterations-3?node-id=219%3A1879)

**Comment by AlexJupiter** [comment]
I also added an iteration illustrating how someone can edit the instance name [here](https://www.figma.com/file/V4GeNtzgy2DY1EJlDGnRiCJK/Instance-management-iterations-3?node-id=221%3A24)

**Comment by yaili** [comment]
I've added some comments in Figma, as you've seen.

**Comment by SaraVieira** [comment]
@AlexJupiter I think most of these are very important for the user to have copiable.

Maybe the login is a little too much , also because you may change your name in the machine and we don't have access to that.

Also if you have more then one CNS name we should have an input for each :)

**Comment by yaili** [comment]
Yes, I was thinking that, the IP and CNS names can actually be loads of inputs, how do we handle that?

**Comment by AlexJupiter** [comment]
New designs for the 'Instance Home' [here](https://www.figma.com/file/ZK5pcMdUpNF96R75ve4NOczr/Instance-Management-iterations-Sprint-4?node-id=38%3A0). @hollowtf when you are a chance an iteration would be appreciated.

**Comment by hollowtf** [comment]
Revised version done, take a look and let me know your thoughts

[Figma](https://www.figma.com/file/ZK5pcMdUpNF96R75ve4NOczr/Instance-Management-iterations-Sprint-4?node-id=86%3A393)

**Comment by hollowtf** [comment]
Feedback from Antonas incorporated. Designs ready for peer review

[Figma](https://www.figma.com/file/ZK5pcMdUpNF96R75ve4NOczr/Instance-Management-iterations-Sprint-4?node-id=94%3A657)

**Comment by AlexJupiter** [comment]
I like this :).

**Comment by hollowtf** [comment]
Final design, tested and approved [Figma](https://www.figma.com/file/ZK5pcMdUpNF96R75ve4NOczr/Instance-Management-iterations-Sprint-4?node-id=94%3A657)
