### ISSUE TITLE
Improve design of tables

### ISSUE THREAD

**Issue by yaili** [yldio/joyent-portal#830]
- [x] Explore alternatives for table header
- [x] Define pattern for reordering
- [x] Include checkbox for select all
- …

**Comment by AlexJupiter** [comment]
@hollowtf could you post a link to the designs you showed us this morning along with a brief description of the changes implemented? Would be useful to have these ideas documented and I'd like to study them in more detail and provide some more feedback :).

**Comment by hollowtf** [comment]
https://www.figma.com/file/Mm72VDV9dljgjci40oQAOzKj/Create-Instance-Package-Table?node-id=16%3A0

Edits made include;

- Increased vertical padding within table components
- Revised table header
- Revised ordering behaviour within the table
- Re-worked sizing and spacing of filter options
- Icons optimised for 24px rendering

**Comment by AlexJupiter** [comment]
- [ ] arrows to be deleted on unsorted columns
- [ ] Mag + SSD
- [ ] Selected state
- [ ] Filter by packages full width
- [ ] Just one filter package
- [ ] Placement of reset filter button
- [ ] A/B test, one design should not have the input filters

**Comment by hollowtf** [comment]
Final feedback incorporated and ready for build

[Figma ](https://www.figma.com/file/Mm72VDV9dljgjci40oQAOzKj/Create-Instance-Package-Table?node-id=16%3A0)
