### ISSUE TITLE
Provisioning limit

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#834]

**Comment by AlexJupiter** [comment]
I've done some initial designs for this [here](https://www.figma.com/file/NVIbR3uRLK4GE2hwjS9P2KAx/Create-instance-mega-accordion-iterations?node-id=272%3A1715) and [here](https://www.figma.com/file/NVIbR3uRLK4GE2hwjS9P2KAx/Create-instance-mega-accordion-iterations?node-id=272%3A2661). I actually think a solution could be a combination of the two, but please let me know your feedback!

If interested some early iterations are also [here](https://www.figma.com/file/NVIbR3uRLK4GE2hwjS9P2KAx/Create-instance-mega-accordion-iterations?node-id=272%3A164) and [here](https://www.figma.com/file/NVIbR3uRLK4GE2hwjS9P2KAx/Create-instance-mega-accordion-iterations?node-id=272%3A0).

**Comment by yaili** [comment]
I think the unavailable mode should be more clear, for example making the entire row 50-40% opacity. I made one row like that in the first link.

**Comment by AlexJupiter** [comment]
Moved this into 'Review', can this be closed?

**Comment by yaili** [comment]
I think so.
