### ISSUE TITLE
Improve adding CNS to an instance

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#835]
We need to improve the distinction between existing CNS and new CNS. Potentially, we can also bring these designs in line with the object designs with Affinity et al.

**Comment by AlexJupiter** [comment]
Morning workshop conducted here: https://www.figma.com/file/eeGGKqYporEBU4SLfkTjLORn/CNS-Workshop

Started work on this here: https://www.figma.com/file/NVIbR3uRLK4GE2hwjS9P2KAx/Create-instance-mega-accordion-iterations?node-id=275%3A1028

Will present to Anthony like this, however realising it will still need more work.

Iterations on tags are definitely needed.

**Comment by AlexJupiter** [comment]
Moved this to 'Review', can be closed now?

**Comment by yaili** [comment]
New prototype: https://www.figma.com/proto/FCelLQ0WOC4EN6ZgTmq5WIXc/Create-instance%3A-mega-accordion-iterations-2?scaling=contain&node-id=1%3A19

**Comment by AlexJupiter** [comment]
Damn, we forgot to show this to Anthony this morning. The only way we can go any further with this is through testing I think. 

I also think that we could potentially get away with a marvel prototype here, what do we think? 

In terms of the design for the tags - this could be something @hollowtf could pick up at a later date.

**Comment by yaili** [comment]
Marvel proto: https://marvelapp.com/115j5f2g/screen/34567744

**Comment by AlexJupiter** [comment]
Proposing we close this....

**Comment by yaili** [comment]
Yes, do we want @hollowtf to improve on it, or fine for v1?

**Comment by AlexJupiter** [comment]
@hollowtf can you have a look at the marvel prototype and tell us what you think?
