### ISSUE TITLE
Define epics and success criteria

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#839]

**Comment by AlexJupiter** [comment]
[Started an initial plan for this here. ](https://docs.google.com/document/d/1XuWxA-VYDjcCRvXTU3DiMopf_E06hCP9p5RMeF4gNfQ/edit)

After a workshop with Antonas, we found that the term “KPIs” are confusing and that they signify that we judge things on a scale, whilst this might be correct, it’s also difficult to quantify and for us to continually judge.

Therefore, we proposed the term “Success Criterias”, these are simple statements that say what the product and then epic (they can possible sit on two levels) should be achieving. 

We can then judge our progress towards achieving this Success Criteria in terms of Confidence
We’ve planned an initial workshop tomorrow (when Sergio is back from holiday) to determine our success criterias for the overall product and then epics. on Thursday once Sergio is back.

It was also discussed that all epics should be on the project ZenHub board at the same time.

**Comment by AlexJupiter** [comment]
Workshop plan for tomorrow morning: https://docs.google.com/document/d/15c3dC3l85V1UI0p-ssLQsptn94xdhWLcRxUd0yUD29k/edit#heading=h.2p2icg66wxxc

**Comment by yaili** [comment]
Are we continuing the workshop this week, or are we closing this?

**Comment by AlexJupiter** [comment]
I think we need to continue this, I'll set up a workshop on Wednesday, and then we can all review the doc beforehand.

**Comment by yaili** [comment]
@AlexJupiter close?

**Comment by AlexJupiter** [comment]
To close I'd like to first of all get some feedback from Casey and then also translate all of our work into new Epics in Zenhub and place them accordingly in the board.

**Comment by yaili** [comment]
OK, moving to review for now then.

**Comment by AlexJupiter** [comment]
Shall I go ahead and transfer all of this into GitHub? Not sure how much feedback we'll receive on the doc.

**Comment by yaili** [comment]
Yes :)
