### ISSUE TITLE
Consider adding icons to instance creation summary to improve readability

### ISSUE THREAD

**Issue by yaili** [yldio/joyent-portal#845]
## I'm submitting a...

  - [ ] bug report
  - [ ] feature request
  - [x] design request

## Other information

Something that Tom could potentially work on next week.

**Comment by yaili** [comment]
Here is a link to the Figma file that Tom can start working from: https://www.figma.com/file/FCelLQ0WOC4EN6ZgTmq5WIXc/Create-instance%3A-mega-accordion-iterations-2?node-id=1%3A322

**Comment by yaili** [comment]
@hollowtf is this in review?

**Comment by yaili** [comment]
@hollowtf can you add a link to the designs?

**Comment by hollowtf** [comment]
[Figma design](https://www.figma.com/file/UXIV7EG06UDEeP4NFlsy0ohk/Create-Instance-Summary?node-id=1%3A17)
