### ISSUE TITLE
Design bulk actions in instance list and snapshots

### ISSUE THREAD

**Issue by yaili** [yldio/joyent-portal#864]
## I'm submitting a...

  - [ ] bug report
  - [ ] feature request
  - [x] design request

## What is the current behavior?

We need to finalise the designs for how bulk actions work in tables/lists in instance management. Things to consider:

- [ ] Background of the bulk actions bar
- [ ] Improved icons
- [ ] Improved layout/spacing
- [ ] Type hierarchy

Latest designs:
- [Figma](https://www.figma.com/file/Ox99vAFeABmr1RvQsQ8sDDJK/Snapshots?node-id=6%3A6)
- [Marvel](https://marvelapp.com/116d7j46/screen/34626153)

**Comment by hollowtf** [comment]
Issue Done;

[Instance list Figma](https://www.figma.com/file/R54EYOFwKGRaAibgCTpHmQe9/Instance-management-iterations-2?node-id=58%3A522)

[Snapshot Figma](https://www.figma.com/file/Ox99vAFeABmr1RvQsQ8sDDJK/Snapshots?node-id=31%3A230)

**Comment by yaili** [comment]
👍 to latest revisions
