### ISSUE TITLE
Improve firewall designs

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#865]
- [x] Do we keep 2 tables or just one table?
- [x] Visual consistency

**Comment by AlexJupiter** [comment]
@hollowtf can we have the latest Figma links here please?

**Comment by hollowtf** [comment]
[Figma design ](https://www.figma.com/file/LI9g2XfX8MnGKgLPro45X1qD/Firewall)

**Comment by AlexJupiter** [comment]
I think that have a toggle for disabled firewall rules is an awesome, awesome idea!

https://www.figma.com/file/ZK5pcMdUpNF96R75ve4NOczr/Instance-Management-iterations-Sprint-4?node-id=49%3A220

Thought @ramitos @SaraVieira ?

**Comment by yaili** [comment]
@hollowtf and I had a quick chat and he's going to remove the green bar that indicates "active". The greyed out already conveys that information, and we already have a similar pattern on the messages (top of the screen).

**Comment by hollowtf** [comment]
@yaili The edits have been done

[Figma](https://www.figma.com/file/LI9g2XfX8MnGKgLPro45X1qD/Firewall?node-id=10%3A1122)
