### ISSUE TITLE
Testing sessions

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#867]

**Comment by AlexJupiter** [comment]
Testing sessions will be on Wednesday 22nd Nov

**Comment by SaraVieira** [comment]
What will be tested here?

**Comment by AlexJupiter** [comment]
Definitely, technical prototype of package selection and technical prototype of affinity.

The rest I think we'll have a clearer idea towards the end of the week.

**Comment by yaili** [comment]
Closing this, created an analysis issue.
