### ISSUE TITLE
Improve CNS designs

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#868]
## I'm submitting a...

  - [ ] bug report
  - [ ] feature request
  - [x] design request

**Comment by yaili** [comment]
@AlexJupiter @ramitos I forgot how this differs from #817

**Comment by AlexJupiter** [comment]
@yaili as we discussed yesterday afternoon, I believe this is a duplicate, right @ramitos ?

**Comment by ramitos** [comment]
@AlexJupiter yes, it is. Thanks for catching that ;)

**Comment by AlexJupiter** [comment]
Okay! Some 'improved' DNS & CNS designs inside instance management for everyone.

[This](https://www.figma.com/file/ZK5pcMdUpNF96R75ve4NOczr/Instance-Management-iterations-Sprint-4?node-id=38%3A181) frame improves the grouping of the information and shows DNS & CNS on their own seperate page for the first time. CNS enable/disable is at the top considering the repercussions of toggling. 

[This](https://www.figma.com/file/ZK5pcMdUpNF96R75ve4NOczr/Instance-Management-iterations-Sprint-4?node-id=49%3A59) frame shows editing service name.

[This](https://www.figma.com/file/ZK5pcMdUpNF96R75ve4NOczr/Instance-Management-iterations-Sprint-4?node-id=49%3A220) frame shows what will happen when CNS is disabled. 

Thoughts?

**Comment by yaili** [comment]
I've added some comments. @hollowtf ?

**Comment by yaili** [comment]
@hollowtf will pick this up later after home designs

**Comment by hollowtf** [comment]
I done a once over this:

-[Disabled state](https://www.figma.com/file/ZK5pcMdUpNF96R75ve4NOczr/Instance-Management-iterations-Sprint-4?node-id=105%3A6)

-[Enabled state](https://www.figma.com/file/ZK5pcMdUpNF96R75ve4NOczr/Instance-Management-iterations-Sprint-4?node-id=94%3A805)

-[Add CNS names](https://www.figma.com/file/ZK5pcMdUpNF96R75ve4NOczr/Instance-Management-iterations-Sprint-4?node-id=107%3A0)
