### ISSUE TITLE
Improve affinity designs

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#873]
## I'm submitting a...

  - [ ] bug report
  - [ ] feature request
  - [x] design request

## What is the current behavior?
@hollowtf did some work on this and we need to review it - and potentially implement

**Comment by hollowtf** [comment]
[Figma design for review](https://www.figma.com/file/PdNDgvbiwwcmiRDx9YxnMlPl/Create-Instance-Affinity?node-id=6%3A837)

**Comment by yaili** [comment]
@hollowtf added my comments, nothing big

**Comment by hollowtf** [comment]
Feedback implemented

[Figma](https://www.figma.com/file/PdNDgvbiwwcmiRDx9YxnMlPl/Create-Instance-Affinity?node-id=6%3A837)

**Comment by yaili** [comment]
Looking good. Thank you.
