### ISSUE TITLE
Improve designs for networks

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#875]
## I'm submitting a...

  - [ ] bug report
  - [ ] feature request
  - [x] design request

## What is the current behavior?
OUr current designs just show the collapsed accordion. We need the expanded accordion as well.

**Comment by yaili** [comment]
@AlexJupiter is this really in progress?

**Comment by AlexJupiter** [comment]
@SaraVieira @ramitos we just conducted a sketching workshop and it would be great to have your opinion.

Before you see the modal, relax, have a coffee and stick with us ;)

![image](https://user-images.githubusercontent.com/7900773/32889664-b9f617e8-cac3-11e7-8533-d2fc89ba17c5.png)

The above consolidated sketch represents the following:
1. The user sees a list of networks they can attach their instance to
2. These networks are displayed in cards (similar to the old service cards on CoPilot and not accordions like our previous design)
3. Inside each of these cards there are two accordions, one accordion for more info (displaying IP, Subnets etc) and another accordion for showing instances on that network
4. In the above sketch, the user has opened the accordion that shows the number of instances on that network. In the sketch we are showing the first three instances (perhaps this can be increased to ~10 in a future iteration)
5. At the bottom of the list of instances there is a 'See all' CTA that then opens out a modal that then shows all instances on that network

Now why did we use a modal? Because:
- With 1000+ potential instances there is no way to show all these instances on the create instance page; let alone inside an accordion on this page
- Opening up a new page raises a great deal of work in terms of navigation of this new page. We thought about opening up a new tab, however again, we couldn't reach an elegant solution here
- Some of the previous issues highlighted around a modal are not as relevant here. For example, a user won't always have to use this modal (it's only used if there are numerous instances on that network) and we can't think of an example when this modal would ever be shared. After all, networks will be managed in a separate 'management console' inside of Triton

**Comment by AlexJupiter** [comment]
Just copying in the Slack conversation for future reference ;)

ramitos [12:08 PM] 
@Tom Holloway @aj @yaili I would probably have pushed for a new page but I do agree you all your points. It would be weird in terms of navigation because it doesn't integrate with anything else


[12:09] 
there is a solution in the future: once we implement network management we can just link to that network (edited)


[12:09] 
but for now I agree with this :+1:


[12:09] 
seems reasonable to me


[12:09] 
we will need to push Casey to implement this method :wink:


yaili [12:10 PM] 
[insert gif of skies opening and light coming through here]

[12:10] 
:pray:

ramitos [12:10 PM] 
:smile:


aj [12:12 PM] 
@ramitos :confetti_ball: :tada:


[12:12] 
@sara.vieira :confused: ? (edited)


yaili [12:13 PM] 
@aj she’s fainted probably



ramitos [12:13 PM] 
ahah


sara.vieira [12:14 PM] 
I died inside


[12:14] 
I don't have a better alternative


[12:14] 
i hate this


ramitos [12:14 PM] 
yeah, that's the problem


[12:14] 
I'm on the hate modals camp


[12:15] 
but I don't have a better solution

**Comment by AlexJupiter** [comment]
If someone could pick this up today, implementing our sketch from Thursday, as well as Casey’s idea about filtering the instance list; that would be cool!

**Comment by yaili** [comment]
Here's a first go at the design: https://www.figma.com/file/NVIbR3uRLK4GE2hwjS9P2KAx/Create-instance-mega-accordion-iterations?node-id=512%3A0

Some notes for feedback:
- Icons are placeholders for now
- Can the accordion be explored in a different way?
- Is the open state different/clear enough from the closed state?

Feedback, please.

**Comment by yaili** [comment]
Update based on feedback: https://www.figma.com/file/NVIbR3uRLK4GE2hwjS9P2KAx/Create-instance-mega-accordion-iterations?node-id=528%3A1129
