### ISSUE TITLE
Put Affinity Components in UI Toolkit

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#882]
## I'm submitting a...

  - [ ] bug report
  - [ ] feature request
  - [x] design request

## What is the current behavior?
there isn't one, so we need to add the new component to the UI Toolki

**Comment by yaili** [comment]
First we need to:
- [ ] Agree on a name
- [ ] Agree on final components

**Comment by yaili** [comment]
Closing as we're creating a more detailed breakdown of what needs to be added
