### ISSUE TITLE
Fix capitalisation of acronyms and abbreviations

### ISSUE THREAD

**Issue by yaili** [yldio/joyent-portal#886]
## I'm submitting a...

  - [x] bug report
  - [ ] feature request
  - [ ] design request

## What is the current behavior?

Abbreviations and acronyms like ID, CNS, DNS are currently forced sentence case (Id, Cns, Dns, etc.)

## What is the expected behavior?

It should be possible to define all-caps, instead of having a blank rule for all titles

**Comment by SaraVieira** [comment]
@yaili Where is this visible ?

**Comment by yaili** [comment]
@SaraVieira I saw it in the navigation of @ramitos demo and also headers in tables
