### ISSUE TITLE
Monitoring and Alerting

### ISSUE THREAD

**Issue by luisklefsjo** [yldio/joyent-portal#89]
Learn about available container monitoring capabilities (thresholds, trends, alerts etc)

https://docs.google.com/a/make-us-proud.com/document/d/1M_lDFzTZSZ-dnP2Z3a8EnoC77qwGZI9zI-ScmEoEibs/edit?usp=sharing

**Comment by ajones5876** [comment]
Documented in wiki: https://github.com/yldio/joyent-portal/wiki/Research and here: https://github.com/yldio/joyent-portal/wiki/22.11.16:-Learn-about-available-container-monitoring-capabilities-(thresholds,-trends,-alerts-etc)
