### ISSUE TITLE
Create Affinity Prototytpe

### ISSUE THREAD

**Issue by SaraVieira** [yldio/joyent-portal#893]
## I'm submitting a...

  - [ ] bug report
  - [x] feature request
  - [ ] design request

## What is the expected behavior?
https://www.figma.com/file/PdNDgvbiwwcmiRDx9YxnMlPl/Create-Instance%3A-Affinity

**Comment by AlexJupiter** [comment]
Are we happy with this overflow for long rules?
![image.png](https://images.zenhubusercontent.com/5888921751aa2c305772cb93/132a1560-ca33-4fbc-b85a-b6a926bd96f5)

**Comment by yaili** [comment]
line height and padding seems too tight, @hollowtf ?

**Comment by hollowtf** [comment]
yeah, line-height on the established "must rulle looks too tight (needs to be 24px). Whilst the line height on the interactive rule looks too loose. CVould we also have the text wrap indented to align with the first word of the rule i.e. 'be' ?
