### ISSUE TITLE
Workshop 1: Sign Up and Onboarding

### ISSUE THREAD

**Issue by luisklefsjo** [yldio/joyent-portal#9]
Sign Up and Onboarding:
https://docs.google.com/a/make-us-proud.com/document/d/1YAzTKA50drT4O3zkscBDF1NzIiIo2ywLYUL_OAvWMco/edit?usp=sharing

**Comment by ajones5876** [comment]
Documented here: https://github.com/yldio/joyent-portal/issues/200
