### ISSUE TITLE
Examples of changed project manifests representing service upgrades and reverts

### ISSUE THREAD

**Issue by misterbisson** [yldio/joyent-portal#90]
See actual manifest changes in https://github.com/autopilotpattern/wordpress/commits/master/docker-compose.yml

- Adding port 443 to Nginx, https://github.com/autopilotpattern/wordpress/commit/5c2279b20e09d570db0e89b2682ec34dd715c3e9#diff-4e5e90c6228fd48698d074241c2ba760
- Adding `prometheus` service, moving `consul` to a different position, https://github.com/autopilotpattern/wordpress/commit/c889a15666293237cc979c0a7ca36c80528009f8#diff-4e5e90c6228fd48698d074241c2ba760
- Changing the command that the image runs, https://github.com/autopilotpattern/wordpress/commit/64423e4a4dd7365cac310cf2a6e624cc9570bc21#diff-4e5e90c6228fd48698d074241c2ba760
- Changing the image versions for many services, changing the list of ports for `consul`, https://github.com/autopilotpattern/wordpress/commit/bed131c19423ffe8d9f9751207087b86d0049f36#diff-4e5e90c6228fd48698d074241c2ba760
- Adding an environment variable to most services, https://github.com/autopilotpattern/wordpress/commit/a41d27b0281a33a2327848417269817509ea3f6e#diff-4e5e90c6228fd48698d074241c2ba760
- Adding affinity settings for most services, https://github.com/autopilotpattern/wordpress/commit/a3b8b7cbf97acf9d5b059da6d291c4002c11a22e#diff-4e5e90c6228fd48698d074241c2ba760

**Comment by yaili** [comment]
Closing. We can come back to this if needed.
