### ISSUE TITLE
Implement feeedback regarding CNS

### ISSUE THREAD

**Issue by yaili** [yldio/joyent-portal#904]
Feedback from testing sessions.

**Comment by hollowtf** [comment]
Instance management CND/DNS
[Figma](https://www.figma.com/file/CUFh7KjVqdZHccrBVBpSnVdn/IM-CNS-DNS?node-id=18%3A116)

Create instance CNS/DNS
[Figma](https://www.figma.com/file/ehwgeXWi3hnt4CNQNGKRoDws/CI-CNS)
