### ISSUE TITLE
Create Tag UI

### ISSUE THREAD

**Issue by SaraVieira** [yldio/joyent-portal#905]
## I'm submitting a...

  - [ ] bug report
  - [x] feature request
  - [ ] design request

## What is the current behavior?
The UI on tags is wrong it should look like:

## What is the expected behavior?
https://www.figma.com/file/cK42HPiq1KHmjtCu1yy766Sd/IM%3A-Tags

**Comment by AlexJupiter** [comment]
We need an estimate @SaraVieira ;)

And do you have a link for it?

I'll also move it into "Progress"
