### ISSUE TITLE
Plan December London sprint

### ISSUE THREAD

**Issue by yaili** [yldio/joyent-portal#907]

**Comment by AlexJupiter** [comment]
I've started going through the initial doc again and creating a 2nd round of more granular, technical questions: https://docs.google.com/document/d/1jrFRpFNVVghfVxQeXhdW9pHWMX8rcPAsNzI8grmB6a0/edit#

These are things I don't understand, that I feel I need to so I can offer some UX guidance and help plan the sprint.

**Comment by AlexJupiter** [comment]
I created a short deck exploring different methods of navigation in preparation for the excercises next week: https://docs.google.com/presentation/d/1E5lbohaqw1SI-Qa4i8myNI8jf_9u2At6xuPEffeZWNk/edit#slide=id.g2a386baed8_0_206
