### ISSUE TITLE
End-of-year slide decks

### ISSUE THREAD

**Issue by yaili** [yldio/joyent-portal#932]
As defined during the London sprint.

**Comment by AlexJupiter** [comment]
UI Toolkit Deck: https://drive.google.com/open?id=10iCvvdP3atDtObOkuoTC9T_eIAzBkqOB1YQCWIqNjRY

Instance Management and Creation Deck: https://drive.google.com/open?id=1J0_Yt3ZcwQ0uqmX1F-TiMciAGLVU_jELU6zv7lOkjFQ
