### ISSUE TITLE
Affinity to only have one rule

### ISSUE THREAD

**Issue by yaili** [yldio/joyent-portal#936]
From London sprint.

You can use Triton CLI or Terraform to create multiple rules.

**Comment by hollowtf** [comment]
Designs have been updated to account for this.

Create Instance:
https://www.figma.com/file/PdNDgvbiwwcmiRDx9YxnMlPl/CI-Affinity

Instance Management:
https://www.figma.com/file/NidiHTD7KDH2SRuXG4b5vEgT/IM-Affinity
