### ISSUE TITLE
Data center configuration text, proximity and component

### ISSUE THREAD

**Issue by yaili** [yldio/joyent-portal#937]
From London sprint.

**Comment by AlexJupiter** [comment]
Design is here: https://www.figma.com/file/Sn39bnneX4wHS0KaWa47c1Fh/CI-Instance-Type-and-Image?node-id=64%3A418

**Comment by ramitos** [comment]
since we have the navigation designed already, I'm going to close this. @yaili feel free to reopen if you see fit
