### ISSUE TITLE
User testing analysis

### ISSUE THREAD

**Issue by yaili** [yldio/joyent-portal#939]
On Wednesday 20th December.

With Hana.

And define initial findings to show Casey.

**Comment by AlexJupiter** [comment]
https://drive.google.com/open?id=1ymz3fjtXF-DUANiQamT1jvb9tK4u_tTABNxIq8W39nA

**Comment by AlexJupiter** [comment]
I'd say this is 90% finished. Need to spend an hour just finishing it off.

**Comment by AlexJupiter** [comment]
@yaili and/or @hollowtf it would be appreciated if you could look this through, so we can close, and send to Casey.

**Comment by yaili** [comment]
Thank you. Latest version is here: https://docs.google.com/presentation/d/1NG6gRMdq9C-XbZ7VCsFNTItSQcLKEZrmWmbtSt5Tbzw/edit#slide=id.g2dd82c75b5_0_0

Just needs a little more feedback to complete.

**Comment by AlexJupiter** [comment]
@yaili cool thanks, what did you improve out of interest? And what can I do more to improve it?

**Comment by AlexJupiter** [comment]
Following feedback from Casey, we can experiment with changing "Services" to "Products and Services".
