### ISSUE TITLE
Improve editing of tags design

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#950]
At the moment it's unclear how a user can edit a tag in instance management and conduct a bulk remove.

**Comment by hollowtf** [comment]
I have updated the tags section of instance management to include alterations for the Edit button (as discussed with Sergio) and have included an empty state when no tags exist.

https://www.figma.com/file/cK42HPiq1KHmjtCu1yy766Sd/IM-Tags?node-id=89%3A115
