### ISSUE TITLE
Update CNS Designs

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#957]
A revision of the designs needs to be conducted across management and creation following the workshops with Casey.

**Comment by hollowtf** [comment]
I have updated the CNS designs to align with Casey's knowledge transfer regarding regarding DNS/CNS. 

I have not included Instance name within the CNS subsection as it does not feel like the appropriate space for that functionality.

Designs for Create Instance:
https://www.figma.com/file/ehwgeXWi3hnt4CNQNGKRoDws/CI-CNS

Designs for Instance Management:
https://www.figma.com/file/CUFh7KjVqdZHccrBVBpSnVdn/IM-CNS-DNS

**Comment by AlexJupiter** [comment]
Following a coupld of workshops I outlined all my learnings on CNS here: https://docs.google.com/document/d/1lBsuA1ucRqvyahKh3lOS8A_-T6Kc0IpK1hYmfIcRFew/edit#heading=h.p27x6ifxg6f

I have also completed a preliminary mockup here: https://www.figma.com/file/ehwgeXWi3hnt4CNQNGKRoDws/CI-CNS?node-id=69%3A2270 I am sure @hollowtf will have improvements though!

**Comment by hollowtf** [comment]
Have made updates in accordance with AJ's observations. 
@ramitos Would be great if you could take a look and see if this makes sense, thanks.

Create Instance:
https://www.figma.com/file/ehwgeXWi3hnt4CNQNGKRoDws/CI-CNS?node-id=69%3A2270

Instance Management:
https://www.figma.com/file/CUFh7KjVqdZHccrBVBpSnVdn/IM-CNS-DNS
