### ISSUE TITLE
Should we display disabled cursor on disabled input? (and toggle)

### ISSUE THREAD

**Issue by yaili** [yldio/joyent-portal#963]
## I'm submitting a...

  - [ ] bug report
  - [ ] feature request
  - [x] design request

## What is the current behavior?

The text input cursor appears

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

- Visit: https://joyent-ui-toolkit.now.sh/#input
- Go to Input > Disabled
- Hover over the input field
- Also in toggle https://joyent-ui-toolkit.now.sh/#toggle

## What is the expected behavior?

Disabled cursor on hover

## What is the motivation / use case for changing the behavior?

It's confusing that it seems like you can interact with the input but you can't

## If the current behavior is a bug, please provide your browser

Chrome Version 63.0.3239.84 (Official Build) (64-bit)

**Comment by AlexJupiter** [comment]
This sounds like a good improvement to me!
