### ISSUE TITLE
Validation messages selects should align right

### ISSUE THREAD

**Issue by yaili** [yldio/joyent-portal#964]
## I'm submitting a...

  - [x] bug report
  - [ ] feature request
  - [ ] design request

## What is the current behavior?

The messages don't seem to align with anything in particular

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

- Visit https://joyent-ui-toolkit.now.sh/#select
- See the validation messages

## What is the expected behavior?

To match input validation messages, they should align right, needs @hollowtf's review

**Comment by AlexJupiter** [comment]
These error validations should surely align to something I agree. 

What would be the rationale for aligning on the right and not left?

The problem I see about aligning right is what happens if the error message is longer than the input, where does the overflow go?

**Comment by hollowtf** [comment]
I agree, the error messages should align left, and we should get rid of the 'Warning' and 'Success' states, no need for them.
