### ISSUE TITLE
Target link in docs not working

### ISSUE THREAD

**Issue by yaili** [yldio/joyent-portal#966]
## I'm submitting a...

  - [x] bug report
  - [ ] feature request
  - [ ] design request

## What is the current behavior?

Clicking on "Target" doesn't take you anywhere. And what is target anyway?

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

- Go to https://joyent-ui-toolkit.now.sh/#tooltip
- Try to click on Target

## What is the expected behavior?

That the link takes you somewhere.

**Comment by ramitos** [comment]
A `<Target />` is an High Order Component that listens for clicks/touches on the children and outside of the children. The `<Target />` is responsible to communicate with the `<Container />` and the `<Container />` decides whether to show the tooltip or not. 

For some reason the tooltip is not working in the live examples. That's something that we need to take a look at
