### ISSUE TITLE
Part Completed and Incomplete icons are cropped

### ISSUE THREAD

**Issue by yaili** [yldio/joyent-portal#970]
## I'm submitting a...

  - [x] bug report
  - [ ] feature request
  - [ ] design request

## What is the current behavior?

These 2 icons are cropped, should be rounded

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

Visit https://joyent-ui-toolkit.now.sh/#functional-iconography
See Part Completed and Incomplete icons

## What is the expected behavior?

They should be circles

**Comment by ramitos** [comment]
Shouldn't certain icons be removed from the ui-toolkit because they are no longer relevant? 

 - Tick
 - Completed
 - Part Completed
 - Incomplete
 - Import
 - Health

@yaili

**Comment by yaili** [comment]
Yes. @hollowtf can confirm the list.

**Comment by hollowtf** [comment]
Here is a full list of icons current of value/in use are:

- Menu
- Action
- Affinity
- Arrow
- Arrow_2
- Chevron
- Clipboard
- Close
- CNS
- CPU
- DataCenter
- Delete
- Edit
- Fabric
- Filter
- Firewall
- GeneralPurpose
- ID
- Import
- Instance
- InstanceType
- Login
- Memory/RAM
- Metadata
- Name
- Network
- Package
- Play
- Private
- Public
- Randomize
- Restart
- Stop
- Storage
- Tags
- Tick
- UserScripts

Completed, Part Completed, Incomplete, and Health can be removed
