### ISSUE TITLE
Write error copy for all sections in create instance

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#976]
## I'm submitting a...

  - [ ] bug report
  - [ ] feature request
  - [x] design request

## What is the current behavior?
A user is not notified of any error when not attaching their instance to a network, creating a duplicate tag etc

## What is the expected behavior?
A user should not be able to deploy an instance that is not attached to a network, and this should be made apparent in the network section in create instance. Perhaps an error state also needs to be designed.

**Comment by AlexJupiter** [comment]
First pass at this: https://docs.google.com/document/d/18-ViBOmjFoS7RRxi0OJblQxpJzHMi3qAOUd-oQs5gkw/edit#

@SaraVieira and @ramitos please do check the technicalities here!

**Comment by AlexJupiter** [comment]
@SaraVieira and @ramitos could one of you give this a look over and let me know your opinion please? This is so I can either close the issue or do another iteration.

**Comment by AlexJupiter** [comment]
Revised the tag error copy on the back on the testing session we just did with Casey.

**Comment by ramitos** [comment]
Added some comments to the doc.

**Comment by AlexJupiter** [comment]
Updated the error states in line with the realisation that some inputs can only start with a letter or number, but can contain ".", "-" or "_" elsewhere.
