### ISSUE TITLE
Design the addition of User Scripts

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#978]
## I'm submitting a...

  - [ ] bug report
  - [ ] feature request
  - [x] design request

## What is the current behavior?
This feature doesn't currently exists, but it needs to.

## What is the expected behavior?
When a user is creating an instance, they want to add user scripts to their instance, so they can boot up their instance in a custom way

## What is the motivation / use case for changing the behavior?
Highlighted as an integral feature by product owner

**Comment by AlexJupiter** [comment]
@hollowtf and I are happy with these designs: https://www.figma.com/file/Xyl8yRIv3QiAdJ6eItudXQ6f/CI-User-Scripts

We believe this is ready to build unless there are any comments.

**Comment by misterbisson** [comment]
LGTM. I added a comment with this new language: 

> Insert code to execute when the machine starts (first boot only for KVM, every boot for infrastructure containers). Learn more about user scripts.
