### ISSUE TITLE
Create instance: Instance type and image

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#980]
https://www.figma.com/file/Sn39bnneX4wHS0KaWa47c1Fh/CI-Instance-Type-and-Image

Complexities:
- mapping images to versions
- creating component

**Comment by AlexJupiter** [comment]
@SaraVieira there are some UI improvements that need to be conducted here. It's hard to tell from the GIF, but when there were only four images in a row the spacing was off. There are a couple of minor things as well that need to be tidied up 

I'm just confirming whether this should be closed or not? Or whether we should create a new issue for bugs/UI improvements?

**Comment by SaraVieira** [comment]
@AlexJupiter the spacing thing was fixed before I merged, I'll share during the stand-up :)

**Comment by AlexJupiter** [comment]
@SaraVieira ah cool! 

Two other bugs we noticed though from the GIF:
- when selecting a version, it's only the top border that turns blue, the whole border needs to turn blue
- with the image tiles, the bottom-right-border-radius and bottom-left-border-radius don't seem to be present (this could be an artifact of the GIF but we weren't sure)
