### ISSUE TITLE
Create Instance: Package

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#981]
https://www.figma.com/file/Mm72VDV9dljgjci40oQAOzKj/CI-Package-Table

Complexities:
- SSD, this needs to be mapped to Fastdisk
- New icons are needed for the category filters
- refactoring code from the prototype

**Comment by AlexJupiter** [comment]
@SaraVieira is this in progress now?

**Comment by SaraVieira** [comment]
yes ,. sorry
