### ISSUE TITLE
Offline First

### ISSUE THREAD

**Issue by tomgco** [yldio/joyent-portal#99]
A panicking site reliability engineer (Sarah) is at their favourite fish and chips shop, however due to a junior developer (Frank) accidently scaling down one of their services, an elevated number of errors are starting to occur.

Frank calls Sarah about the issue, and isn't sure what the problem is.
Sarah says that she will fix the issue, however the fish and chip shop has very poor reception on her mobile.
She opens the Joyent Portal on her mobile, and navigates to the service that is having an issue.
(At this point she loses reception)
She selects to scale the service up by 3 nodes.
(at the same time, Frank takes the initiative to also scale the service by two nodes)
Sarah finally manages to get reception, but at this point the update to say that another action had already happened.
Sarah checks that everything is now working as expected.
It is, Sarah then continues to tuck into her fish and chips.

**Comment by ramitos** [comment]
should be incorporated into CI using lighthouse
