### ISSUE TITLE
Review tag designs

### ISSUE THREAD

**Issue by AlexJupiter** [yldio/joyent-portal#990]
Make sure that new new designs are ready to be implemented.

**Comment by AlexJupiter** [comment]
@hollowtf and I are happy with these designs: https://www.figma.com/file/b5GBfXdP4C1FLK8qsaCU4K7O/CI-Tags

Will close unless there are any comments.

**Comment by misterbisson** [comment]
:pickles:

(Pickles means "ship it" where I come from.)
