### ISSUE TITLE
Cross-browser testing

### ISSUE THREAD

**Issue by yaili** [yldio/joyent-portal#992]
It would be good to have a list of bugs across browsers. 

Perhaps we can divide that list by how bad the portal is broken, e.g. does the bug block access to content or navigation, is it critical to fix, can it wait, etc.

Browsers to test (provisional list):
- Chrome (lastest 3 versions)
- Firefox (latest 3 versions)
- Internet Explorer 11
- Microsoft Edge 12
- Safari (at least latest, ideally 7, 8 and 9)
- Safari mobile
- Samsung Internet Browser

**Comment by AlexJupiter** [comment]
@yaili how do you propose we conduct this? 

I see us doing a test on the UI Toolkit, and then another test with the whole Instance Management and Creation portal once it's ready to be released. What are you thoughts?

I'd also like to propose changing the tag to design, this definitely sounds like something I can do to save engineering time.

**Comment by AlexJupiter** [comment]
My notes are being made in here: https://docs.google.com/document/d/1SSycCAEtv9IYfYnF1fAU0b3bEurDu0TCsRixdHGUDTM/edit
